import {and,eq,asc,lt,or} from 'drizzle-orm';
import {randomUUID} from 'node:crypto';
import {z} from 'zod';
import {media,directUploads,driveConnections} from '../../../db/production-schema';
import {projects,occurrences} from '../../../db/programme-schema';
import {type DB,ProductionError,lock,active} from '../../production/access';
import {AccessError} from '../../team/service';
import {mediaService,type UploadActor} from '../../production/media-service';
import {google,DriveError,connectionToken,folder,ensureRootFolderName,metaFields,assertSessionUri,seal,unseal} from './google';
const input=z.object({projectId:z.uuid(),occurrenceId:z.uuid().nullable(),uploadKey:z.uuid(),name:z.string().trim().min(1).max(240),mime:z.enum(['image/jpeg','image/png','image/webp','image/heic','image/heif','video/mp4','video/quicktime','application/pdf']),size:z.number().int().positive().max(5*1024**4),sha256:z.string().regex(/^[a-f0-9]{64}$/),category:z.enum(['rush','deliverable']),note:z.string().max(1000).default(''),guestName:z.string().max(100).default('')});
export function folderPlan(title:string,date:string,projectId:string,occurrenceId:string|null,category:string,mime:string){const name=title.replace(/[\u0000-\u001f/\\]/g,' ').trim().slice(0,140);return [{key:`year:${date.slice(0,4)}`,name:date.slice(0,4)},{key:`event:${projectId}:${occurrenceId||'period'}`,name:`${date} — ${name}`},{key:`category:${category}`,name:category==='rush'?'Rushs':'Livrables'},{key:`type:${mime.startsWith('image/')?'photo':mime.startsWith('video/')?'video':'document'}`,name:mime.startsWith('image/')?'Photos':mime.startsWith('video/')?'Vidéos':'Documents'}];}
export function verifyReceipt(f:any,m:typeof media.$inferSelect,u:typeof directUploads.$inferSelect,c:typeof driveConnections.$inferSelect){if(f.id!==u.driveFileId||f.trashed||Number(f.size)!==m.size||f.sha256Checksum!==m.sha256||f.mimeType!==m.mime||f.appProperties?.cometernelUpload!==u.id||f.appProperties?.cometernelOrg!==m.organizationId||!f.parents?.some((p:string)=>p===c.inboxId||p===u.folderId))throw new ProductionError('Le fichier Drive ne correspond pas à cet envoi.');}
export function directDriveService(db:DB){
 const ms=mediaService(db);
 async function owned(who:UploadActor,id:string){z.uuid().parse(id);const [u]=await db.select().from(directUploads).where(eq(directUploads.mediaId,id));const [m]=await db.select().from(media).where(eq(media.id,id));if(!u||!m)throw new AccessError();const a=await ms.authorizeDirect(who,m.projectId,m.occurrenceId,m.category);if(a.org!==m.organizationId||a.userId!==m.createdBy||a.collectionId!==m.collectionId)throw new AccessError();return {u,m};}
 async function conn(id:string,org:string){const [c]=await db.select().from(driveConnections).where(and(eq(driveConnections.id,id),eq(driveConnections.organizationId,org)));if(!c)throw new ProductionError('Drive de l’association indisponible.');return c;}
 return {
 async begin(who:UploadActor,raw:unknown){const v=input.parse(raw);const a=await ms.authorizeDirect(who,v.projectId,v.occurrenceId,v.category);if(a.uploadOnly&&v.mime==='application/pdf')throw new AccessError();
 return db.transaction(async tx=>{await lock(tx,a.org);await ms.authorizeDirect(who,v.projectId,v.occurrenceId,v.category);const [c]=await tx.select().from(driveConnections).where(eq(driveConnections.organizationId,a.org));if(!c)throw new ProductionError('Un administrateur doit connecter le Drive de votre association dans Réglages.');const token=await connectionToken(db,c);
 let [m]=await tx.select().from(media).where(and(eq(media.organizationId,a.org),eq(media.uploadKey,v.uploadKey)));
 let u:typeof directUploads.$inferSelect|undefined;
 if(m){if(m.createdBy!==a.userId||m.collectionId!==a.collectionId||m.sha256!==v.sha256||m.size!==v.size||m.projectId!==v.projectId||m.occurrenceId!==v.occurrenceId||m.category!==v.category)throw new AccessError();[u]=await tx.select().from(directUploads).where(eq(directUploads.mediaId,m.id));if(!u||u.connectionId!==c.id)throw new ProductionError('Cet envoi appartient à une autre connexion.');if(u.status!=='uploading')return {id:m.id,status:u.status};if(u.sessionUri&&u.sessionExpiresAt!>new Date())return {id:m.id,status:u.status,uri:unseal(u.sessionUri,`upload:${u.id}`)};
 // A lost final response must not create a second Drive file when the session expires.
 let existing;try{existing=await google(token,`files/${u.driveFileId}?fields=${metaFields}`);}catch(error){if(!(error instanceof DriveError)||error.status!==404)throw error;}
 if(existing){verifyReceipt(existing,m,u,c);await tx.update(media).set({state:'received',received:m.size}).where(eq(media.id,m.id));await tx.update(directUploads).set({status:'ready',sessionUri:null,sessionExpiresAt:null}).where(eq(directUploads.id,u.id));return {id:m.id,status:'ready'};}
}
 else{if(a.collectionId){const deposits=await tx.select({size:media.size}).from(media).where(eq(media.collectionId,a.collectionId));if(deposits.length>=a.maxFiles!||deposits.reduce((n,x)=>n+x.size,0)+v.size>a.maxBytes!)throw new ProductionError('La limite de ce lien de collecte est atteinte.');}[m]=await tx.insert(media).values({...v,organizationId:a.org,createdBy:a.userId,collectionId:a.collectionId}).returning();}
 const uid=u?.id||randomUUID();const ids=await google(token,'files/generateIds?count=1&space=drive&type=files');const driveFileId=ids.ids[0];
 const r=await fetch('https://www.googleapis.com/upload/drive/v3/files?uploadType=resumable',{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json','x-upload-content-type':v.mime,'x-upload-content-length':String(v.size),origin:new URL(process.env.BETTER_AUTH_URL!).origin},body:JSON.stringify({id:driveFileId,name:v.name,mimeType:v.mime,parents:[c.inboxId],appProperties:{cometernelUpload:uid,cometernelOrg:a.org}}),signal:AbortSignal.timeout(20000)});if(!r.ok||!r.headers.get('location'))throw new ProductionError('Impossible de préparer l’envoi direct dans Drive.');const uri=assertSessionUri(r.headers.get('location')!);const values={organizationId:a.org,mediaId:m.id,connectionId:c.id,driveFileId,sessionUri:seal(uri,`upload:${uid}`),sessionExpiresAt:new Date(Date.now()+6*86400000)};
 if(u)await tx.update(directUploads).set(values).where(eq(directUploads.id,uid));else await tx.insert(directUploads).values({id:uid,...values});return {id:m.id,status:'uploading',uri};});},
 async status(who:UploadActor,id:string){const {u,m}=await owned(who,id);if(u.status!=='uploading')return {status:u.status,received:m.size};if(!u.sessionUri)throw new ProductionError('Session expirée : reprenez le même fichier.');const uri=assertSessionUri(unseal(u.sessionUri,`upload:${u.id}`));const r=await fetch(uri,{method:'PUT',headers:{'content-length':'0','content-range':`bytes */${m.size}`},signal:AbortSignal.timeout(20000)});if(r.status===308){const range=r.headers.get('range');return {status:'uploading',received:range?Number(range.split('-')[1])+1:0};}if(r.ok)return {status:'uploaded',received:m.size};if([404,410].includes(r.status)){await db.update(directUploads).set({sessionUri:null,sessionExpiresAt:null}).where(eq(directUploads.id,u.id));throw new ProductionError('Session expirée : cliquez de nouveau sur Envoyer / reprendre.');}throw new ProductionError('Drive est temporairement indisponible. Reprenez le même fichier.');},
 async complete(who:UploadActor,id:string){const {u,m}=await owned(who,id);if(u.status!=='uploading')return {id,status:u.status};const c=await conn(u.connectionId,m.organizationId);const token=await connectionToken(db,c);const f=await google(token,`files/${u.driveFileId}?fields=${metaFields}`);verifyReceipt(f,m,u,c);await db.transaction(async tx=>{await tx.update(media).set({state:'received',received:m.size,reviewReason:'Fichier reçu directement dans Drive ; taille et empreinte vérifiées.'}).where(eq(media.id,id));await tx.update(directUploads).set({status:'ready',sessionUri:null,sessionExpiresAt:null}).where(and(eq(directUploads.id,u.id),eq(directUploads.status,'uploading')));});return {id,status:'ready'};},
 async claim(){return db.transaction(async tx=>{const rows=await tx.select().from(directUploads).where(or(eq(directUploads.status,'ready'),and(eq(directUploads.status,'classifying'),lt(directUploads.leaseUntil,new Date())))).orderBy(asc(directUploads.createdAt)).limit(1).for('update',{skipLocked:true});const u=rows[0];if(!u)return {job:null};if(u.attempts>=5){await tx.update(directUploads).set({status:'failed',errorCode:'retry_limit'}).where(eq(directUploads.id,u.id));return {job:null};}const leaseId=randomUUID();await tx.update(directUploads).set({status:'classifying',leaseId,leaseUntil:new Date(Date.now()+120000),attempts:u.attempts+1}).where(eq(directUploads.id,u.id));return {job:{id:u.id,leaseId,organizationId:u.organizationId}};});},
 async classify(id:string,leaseId:string){z.uuid().parse(id);z.uuid().parse(leaseId);return db.transaction(async tx=>{
 const [u]=await tx.select().from(directUploads).where(eq(directUploads.id,id));if(!u||u.leaseId!==leaseId||!['classifying','classified'].includes(u.status)||!u.leaseUntil||u.leaseUntil<new Date())throw new AccessError();await lock(tx,u.organizationId);
 const [m]=await tx.select().from(media).where(and(eq(media.id,u.mediaId),eq(media.organizationId,u.organizationId)));if(!m||m.state!=='received'||m.rights?.withdrawn)throw new ProductionError('Fichier indisponible pour le classement.');const c=await conn(u.connectionId,u.organizationId);const token=await connectionToken(db,c);const [p]=await tx.select().from(projects).where(and(eq(projects.id,m.projectId),eq(projects.organizationId,u.organizationId)));if(!p)throw new AccessError();await active(tx,p,m.occurrenceId);const [e]=m.occurrenceId?await tx.select().from(occurrences).where(eq(occurrences.id,m.occurrenceId)):[];
 let dest=await ensureRootFolderName(token,c.rootId,u.organizationId);for(const item of folderPlan(p.title,e?.startDate||p.startDate,p.id,m.occurrenceId,m.category,m.mime))dest=await folder(token,dest,item.key,item.name,u.organizationId);
 // Persist the intended destination before moving: a retry accepts a file already there.
 await tx.update(directUploads).set({folderId:dest}).where(eq(directUploads.id,id));const f=await google(token,`files/${u.driveFileId}?fields=${metaFields}`);verifyReceipt(f,m,{...u,folderId:dest},c);
 if(!f.parents.includes(dest))await google(token,`files/${u.driveFileId}?${new URLSearchParams({addParents:dest,removeParents:c.inboxId,fields:'id,parents'})}`,'PATCH',{});
 const done=await google(token,`files/${u.driveFileId}?fields=${metaFields}`);verifyReceipt(done,m,{...u,folderId:dest},c);if(!done.parents.includes(dest))throw new ProductionError('Classement Drive non confirmé.');await tx.update(directUploads).set({status:'classified',folderId:dest,completedAt:new Date(),errorCode:null}).where(eq(directUploads.id,id));return {status:'classified'};
 });}
 };
}
