import Link from 'next/link';
import { eq } from 'drizzle-orm';
import { programmeContext, MissingSpace } from '../../../modules/programme/context';
import { liturgicalDates } from '../../../db/programme-schema';
import { ProgrammeForm } from '../../../components/programme-form';
import { Badge } from '../../../components/ui/badge';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Sources liturgiques' };
export default async function Page({ searchParams }: { searchParams: Promise<{ organisation?: string }> }) {
  const { org, db } = await programmeContext((await searchParams).organisation); if (!org) return <MissingSpace/>;
  const references = await db.select().from(liturgicalDates).where(eq(liturgicalDates.organizationId, org.id));
  const fields = (entry?: typeof liturgicalDates.$inferSelect) => <><label>Intitulé<input name="title" required minLength={2} maxLength={120} defaultValue={entry?.title}/></label><label>Date<input name="date" type="date" required defaultValue={entry?.date}/></label><label>Tradition<input name="tradition" required minLength={2} maxLength={120} defaultValue={entry?.tradition}/></label><label>Calendrier local / communauté de référence<input name="localCalendar" required minLength={2} maxLength={120} defaultValue={entry?.localCalendar}/></label><label>Source (document, page ou référence vérifiable)<textarea name="source" required minLength={5} maxLength={1000} defaultValue={entry?.source}/></label><label className="check-label"><input type="checkbox" name="verified"/>J’ai vérifié cette date et sa source pour le calendrier indiqué.</label><p className="hint">Toute correction retire la vérification précédente, sauf si vous confirmez une nouvelle vérification.</p><button>{entry ? 'Enregistrer la correction' : 'Ajouter la référence'}</button></>;
  return <><section className="page-title"><p className="eyebrow">SOURCES LITURGIQUES · {org.name}</p><h1>Des dates documentées, une tradition explicite.</h1><p>Aucune date n’est inventée ou préremplie. Les références non vérifiées restent signalées.</p></section><Link href={`/calendrier?organisation=${org.id}&liturgie=1`}>← Retour au calendrier</Link><div className="grid section-spaced"><section className="card"><h2>Références de l’espace</h2>{references.length ? references.map(entry => <article key={entry.id}><h3>{entry.title} · {entry.date}</h3><Badge tone={entry.verifiedAt ? 'success' : 'warning'}>{entry.verifiedAt ? 'Vérifiée par un responsable' : 'À vérifier'}</Badge><p>{entry.tradition} · {entry.localCalendar}</p><p className="preserve-text">Source : {entry.source}</p>{entry.verifiedAt && <p className="hint">Vérification enregistrée le {entry.verifiedAt.toLocaleDateString('fr-FR',{ timeZone: org.timezone })}.</p>}{org.role === 'admin' && <details><summary>Corriger ou revérifier</summary><ProgrammeForm fields={{ operation: 'liturgy', organizationId: org.id, id: entry.id, revision: entry.revision }}>{fields(entry)}</ProgrammeForm></details>}</article>) : <p>Aucune référence ajoutée. Un administrateur peut saisir une date à partir d’une source identifiée.</p>}</section>{org.role === 'admin' && <section className="card"><h2>Ajouter une date</h2><p>Une connexion de moins de cinq minutes est nécessaire. <Link href="/connexion">Me reconnecter</Link></p><ProgrammeForm fields={{ operation: 'liturgy', organizationId: org.id }}>{fields()}</ProgrammeForm></section>}</div></>;
}
