import Link from 'next/link';
import { Temporal } from '@js-temporal/polyfill';
import { programmeContext, MissingSpace, SpaceNavigation } from '../../modules/programme/context';
import { programmeService } from '../../modules/programme/service';
import { calendarRange, calendarEventDates, isoDate, todayIn } from '../../modules/programme/dates';
import { Badge } from '../../components/ui/badge';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Calendrier' };
type Entry = { id: string; title: string; start: string; end: string; href?: string; detail: string; cancelled: boolean; liturgy: boolean; source?: string; verified?: boolean };
export default async function Page({ searchParams }: { searchParams: Promise<{ organisation?: string; date?: string; vue?: string; liturgie?: string; tradition?: string }> }) {
  const query = await searchParams; const { actor, db, org, spaces } = await programmeContext(query.organisation); if (!org) return <MissingSpace/>;
  const data = await programmeService(db).calendar(actor, org.id); const anchor = isoDate.safeParse(query.date).success ? query.date! : todayIn(org.timezone); const view = ['year','month','week','list'].includes(query.vue || '') ? query.vue! : 'month'; const range = calendarRange(anchor, view);
  const entries: Entry[] = data.events.map(e => { const p = data.projects.find(p => p.id === e.projectId)!; return { id: e.id, title: p.title, ...calendarEventDates(e, org.timezone), href: `/projets/${p.id}?organisation=${org.id}`, detail: p.allDay ? 'Journée entière' : `${e.startAt?.toLocaleTimeString('fr-FR', { timeZone: org.timezone, hour: '2-digit', minute: '2-digit' })} · ${org.timezone}`, cancelled: e.status === 'cancelled', liturgy: false }; });
  entries.push(...data.projects.filter(p => p.kind === 'campaign').map(p => ({ id: p.id, title: p.title, start: p.startDate, end: p.endDate, href: `/projets/${p.id}?organisation=${org.id}`, detail: 'Campagne · période', cancelled: p.status === 'cancelled', liturgy: false })));
  if (query.liturgie === '1') entries.push(...data.liturgy.filter(l => !query.tradition || l.tradition === query.tradition).map(l => ({ id: l.id, title: l.title, start: l.date, end: l.date, detail: `${l.tradition} · ${l.localCalendar}`, source: l.source, cancelled: false, liturgy: true, verified: Boolean(l.verifiedAt) })));
  const visible = entries.filter(e => e.start <= range.end && e.end >= range.start).sort((a,b) => a.start.localeCompare(b.start) || a.title.localeCompare(b.title));
  const link = (date: string, vue = view) => `/calendrier?${new URLSearchParams({ organisation: org.id, date, vue, liturgie: query.liturgie || '0', tradition: query.tradition || '' })}`;
  const date = Temporal.PlainDate.from(anchor); const move = view === 'year' ? { years: 1 } : view === 'week' ? { days: 7 } : { months: 1 };
  const renderEntry = (entry: Entry) => <div className={`calendar-entry${entry.cancelled ? ' cancelled' : ''}${entry.liturgy ? ' liturgy-entry' : ''}`} key={entry.id}>{entry.href ? <Link href={entry.href}>{entry.title}</Link> : <strong>{entry.title}</strong>}<small>{entry.detail}</small>{entry.cancelled && <Badge tone="warning">Annulé</Badge>}{entry.liturgy && <><Badge tone={entry.verified ? 'success' : 'warning'}>{entry.verified ? 'Source vérifiée' : 'À vérifier'}</Badge><details><summary>Provenance</summary><p>{entry.source}</p></details></>}</div>;
  const cells = view === 'week' ? 7 : Temporal.PlainDate.from(range.start).daysInMonth;
  const offset = view === 'month' ? Temporal.PlainDate.from(range.start).dayOfWeek - 1 : 0;
  return <><section className="page-title"><p className="eyebrow">CALENDRIER · {org.name}</p><h1>Une vue commune du programme.</h1><p>Fuseau de l’association : {org.timezone}. Les horaires sont affichés dans ce fuseau ; les journées entières conservent leur date.</p></section><SpaceNavigation spaces={spaces} selected={org.id} path="/calendrier"/><form className="calendar-controls"><input name="organisation" type="hidden" value={org.id}/><label>Date de référence<input type="date" name="date" defaultValue={anchor} required min="2000-01-01" max="2100-12-31"/></label><label>Vue<select name="vue" defaultValue={view}><option value="year">Année</option><option value="month">Mois</option><option value="week">Semaine</option><option value="list">Liste sur 12 mois</option></select></label><label className="check-label"><input type="checkbox" name="liturgie" value="1" defaultChecked={query.liturgie === '1'}/>Superposer les dates liturgiques</label><label>Tradition<select name="tradition" defaultValue={query.tradition || ''}><option value="">Toutes les traditions saisies</option>{[...new Set(data.liturgy.map(l => l.tradition))].map(t => <option key={t}>{t}</option>)}</select></label><button>Afficher</button></form><div className="section-head"><Link href={link(date.subtract(move).toString())}>← Période précédente</Link><strong>{range.start} → {range.end}</strong><Link href={link(date.add(move).toString())}>Période suivante →</Link></div>
    {view === 'year' ? <div className="year-grid">{Array.from({ length: 12 }, (_, i) => { const month = `${date.year}-${String(i + 1).padStart(2,'0')}-01`; const end = Temporal.PlainDate.from(month).add({ months: 1 }).subtract({ days: 1 }).toString(); const rows = visible.filter(e => e.start <= end && e.end >= month); return <section className="card" key={month}><h2><Link href={link(month,'month')}>{new Intl.DateTimeFormat('fr-FR',{ month:'long', timeZone:'UTC' }).format(new Date(`${month}T12:00:00Z`))}</Link></h2><p>{rows.length} entrée(s)</p>{rows.slice(0,3).map(renderEntry)}{rows.length > 3 && <Link href={link(month,'month')}>Voir les autres entrées →</Link>}</section>; })}</div> : view === 'list' ? <section className="card"><ul className="item-list">{visible.map(e => <li key={e.id}><time dateTime={e.start}>{e.start}{e.end !== e.start ? ` → ${e.end}` : ''}</time>{renderEntry(e)}</li>)}</ul></section> : <div className="calendar-scroll"><div className="calendar-grid" role="table" aria-label={view === 'week' ? 'Calendrier de la semaine' : 'Calendrier du mois'}><div className="calendar-week" role="row">{['Lundi','Mardi','Mercredi','Jeudi','Vendredi','Samedi','Dimanche'].map(day => <div role="columnheader" key={day}>{day}</div>)}</div>{Array.from({ length: Math.ceil((offset+cells)/7) }, (_, row) => <div className="calendar-week" role="row" key={row}>{Array.from({ length: 7 }, (_, col) => { const index = row*7+col-offset; if (index < 0 || index >= cells) return <div role="cell" className="calendar-day blank" key={col}/>; const day = Temporal.PlainDate.from(range.start).add({ days:index }).toString(); return <div role="cell" className="calendar-day" key={col}><time dateTime={day}>{day.slice(-2)}</time>{visible.filter(e => e.start <= day && e.end >= day).map(renderEntry)}</div>; })}</div>)}</div></div>}
    {!visible.length && <p className="gentle-note">Aucune entrée accessible dans cette période. Changez la période ou créez un projet.</p>}<div className="quick-actions section-spaced"><Link className="button secondary" href={`/projets?organisation=${org.id}`}>Mes projets</Link><Link className="button secondary" href={`/calendrier/liturgie?organisation=${org.id}`}>Sources du calendrier liturgique</Link></div><p className="hint">Les annulations restent visibles. Les archives sont consultables dans Projets. Aucune synchronisation Google Calendar et aucun rappel ne sont actifs.</p></>;
}
