import {actionComment} from './comment';
import { createHash } from 'node:crypto';
import { and, eq, isNull, inArray, asc } from 'drizzle-orm';
import { z } from 'zod';
import { getDb } from '../../db/client';
import { organizations } from '../../db/schema';
import { members, projectGrants } from '../../db/team-schema';
import { user } from '../../db/auth-schema';
import { projects, briefs, occurrences } from '../../db/programme-schema';
import { workTasks, workHistory, packPreviews, packApplications, taskDependencies, availabilities } from '../../db/work-schema';
import { AccessError, type Actor } from '../team/service';
import { programmeService } from '../programme/service';
import { isoDate, todayIn } from '../programme/dates';
import { requestLabels, taskLabels, requestTransitions, taskTransitions, type RequestStatus, type TaskStatus } from './models';
import { planPack, hasCycle } from './planning';
type DB=ReturnType<typeof getDb>;type Tx=Parameters<Parameters<DB['transaction']>[0]>[0];type Conn=DB|Tx;
export class WorkError extends Error {}
const reasonSchema=z.string().trim().min(5).max(1000);
const rowSchema=z.object({key:z.string().min(1).max(100),title:z.string().trim().min(3).max(200),description:z.string().trim().max(5000).default(''),format:z.string().trim().max(100),dueDate:isoDate,assigneeId:z.uuid().nullable(),deputyId:z.uuid().nullable()});
export function workService(db:DB) {
 async function membership(c:Conn,a:Actor,org:string) {z.uuid().parse(org);if(!a.user.emailVerified)throw new AccessError();const [m]=await c.select().from(members).where(and(eq(members.organizationId,org),eq(members.userId,a.user.id),isNull(members.revokedAt)));if(!m)throw new AccessError();return m;}
 async function guard(c:Conn,a:Actor,org:string,id:string,edit=false) {z.uuid().parse(id);const m=await membership(c,a,org);const [p]=await c.select().from(projects).where(and(eq(projects.id,id),eq(projects.organizationId,org)));const grants=await c.select().from(projectGrants).where(and(eq(projectGrants.memberId,m.id),eq(projectGrants.projectId,id)));if(!p || !(m.role==='admin'||m.permissions.includes('project.edit')||(!edit&&m.permissions.includes('project.read'))) || (m.role!=='admin'&&!grants.some(g=>g.permission==='project.edit'||(!edit&&g.permission==='project.read'))))throw new AccessError();return {p,m};}
 async function lock(tx:Tx,org:string){z.uuid().parse(org);await tx.select({id:organizations.id}).from(organizations).where(eq(organizations.id,org)).for('update');}
 async function scope(c:Conn,p:typeof projects.$inferSelect,id:string|null){if(p.kind==='campaign'){if(id)throw new WorkError('Une campagne utilise sa période.');return {anchor:p.startDate,key:'project'};}if(!id)throw new WorkError('Choisissez une occurrence.');z.uuid().parse(id);const [e]=await c.select().from(occurrences).where(and(eq(occurrences.id,id),eq(occurrences.projectId,p.id)));if(!e||e.status==='cancelled')throw new WorkError('Occurrence annulée ou indisponible.');return {anchor:e.startDate,key:e.id};}
 async function active(c:Conn,p:typeof projects.$inferSelect){const [b]=await c.select().from(briefs).where(eq(briefs.projectId,p.id));if(p.status!=='preparation'||b?.status!=='accepted')throw new WorkError('Le projet doit être actif et sa demande acceptée.');return b;}
 async function candidate(c:Conn,org:string,projectId:string,id:string|null){if(!id)return;const [m]=await c.select().from(members).where(and(eq(members.id,id),eq(members.organizationId,org),isNull(members.revokedAt)));const grants=await c.select().from(projectGrants).where(and(eq(projectGrants.memberId,id),eq(projectGrants.projectId,projectId)));if(!m||!(m.role==='admin'||m.permissions.some(p=>['project.read','project.edit'].includes(p)))||(m.role!=='admin'&&!grants.some(g=>['project.read','project.edit'].includes(g.permission))))throw new WorkError('Cette personne doit avoir accès au projet avant de recevoir une mission.');}
 async function history(tx:Tx,a:Actor,projectId:string,action:string,reason:string,taskId?:string){await tx.insert(workHistory).values({actorId:a.user.id,projectId,action,reason,taskId});}
 async function task(c:Conn,projectId:string,id:string,revision?:number){z.uuid().parse(id);const [t]=await c.select().from(workTasks).where(and(eq(workTasks.id,id),eq(workTasks.projectId,projectId)));if(!t)throw new AccessError();if(revision!==undefined&&t.revision!==revision)throw new WorkError('Cette tâche a changé. Actualisez avant de recommencer.');return t;}
 return {
 async list(a:Actor,org:string){const m=await membership(db,a,org);const ps=await programmeService(db).list(a,org);const tasks=ps.length?await db.select().from(workTasks).where(inArray(workTasks.projectId,ps.map(p=>p.id))).orderBy(asc(workTasks.dueDate)):[];const availability=await db.select().from(availabilities).where(and(eq(availabilities.organizationId,org),eq(availabilities.memberId,m.id)));return {tasks,projects:ps,member:m,availability};},
 async get(a:Actor,org:string,id:string){const base=await programmeService(db).get(a,org,id);const m=await membership(db,a,org);const tasks=await db.select().from(workTasks).where(eq(workTasks.projectId,id)).orderBy(asc(workTasks.dueDate));const people=await db.select({member:members,name:user.name,email:user.email}).from(members).innerJoin(user,eq(members.userId,user.id)).where(and(eq(members.organizationId,org),isNull(members.revokedAt)));const candidates=[];for(const person of people){try{await candidate(db,org,id,person.member.id);candidates.push(person);}catch{/* Unreadable projects never grant implicit access. */}}const availability=candidates.length?await db.select().from(availabilities).where(inArray(availabilities.memberId,candidates.map(p=>p.member.id))):[];const history=await db.select().from(workHistory).where(eq(workHistory.projectId,id)).orderBy(asc(workHistory.createdAt));const dependencies=tasks.length?await db.select().from(taskDependencies).where(inArray(taskDependencies.taskId,tasks.map(t=>t.id))):[];return {...base,member:m,tasks,candidates,availability,history,dependencies};},
 async decide(a:Actor,org:string,id:string,revision:number,status:RequestStatus,reason:string){z.enum(['received','clarify','accepted','deferred','refused']).parse(status);reason=actionComment(reason,['refused','deferred','clarify'].includes(status),'Décision : '+requestLabels[status]);return db.transaction(async tx=>{await lock(tx,org);const {p,m}=await guard(tx,a,org,id,true);const [b]=await tx.select().from(briefs).where(eq(briefs.projectId,id));if(!b||b.revision!==revision)throw new WorkError('La demande a changé. Actualisez.');if(p.status!=='preparation'||!requestTransitions[b.status as RequestStatus]?.includes(status))throw new WorkError('Cette transition de demande est indisponible.');if(m.role!=='admin'&&m.id!==b.decisionMakerId&&m.id!==p.deputyId)throw new AccessError('La décision revient au décideur, à son suppléant ou à un administrateur ayant accès au projet.');await tx.update(briefs).set({status,revision:b.revision+1,decisionReason:reason,decidedBy:a.user.id,decidedAt:new Date()}).where(eq(briefs.id,b.id));await history(tx,a,id,`request_${status}`,reason);});},
 async preview(a:Actor,org:string,id:string,pack:unknown,occurrenceId:string|null,shift:boolean){const name=z.enum(['essential','standard','extended']).parse(pack);return db.transaction(async tx=>{await lock(tx,org);const {p}=await guard(tx,a,org,id,true);const b=await active(tx,p);const s=await scope(tx,p,occurrenceId);const plan=planPack(name,s.anchor,todayIn(p.timezone),shift,p.revision,b.revision,occurrenceId);const [preview]=await tx.insert(packPreviews).values({projectId:id,createdBy:a.user.id,plan,expiresAt:new Date(Date.now()+30*60_000)}).returning();return preview;});},
 async readPreview(a:Actor,org:string,id:string){z.uuid().parse(id);const [preview]=await db.select().from(packPreviews).where(eq(packPreviews.id,id));if(!preview||preview.createdBy!==a.user.id)throw new AccessError();await guard(db,a,org,preview.projectId,true);const [application]=await db.select().from(packApplications).where(and(eq(packApplications.projectId,preview.projectId),eq(packApplications.scopeKey,preview.plan.scopeKey)));return {...preview,application:application||null};},
 async apply(a:Actor,org:string,previewId:string,input:unknown,lateReason:string){const rows=z.array(rowSchema).min(1).max(20).parse(input);const hash=createHash('sha256').update(JSON.stringify({rows,lateReason})).digest('hex');return db.transaction(async tx=>{await lock(tx,org);z.uuid().parse(previewId);const [v]=await tx.select().from(packPreviews).where(eq(packPreviews.id,previewId));if(!v||v.createdBy!==a.user.id)throw new AccessError();const {p}=await guard(tx,a,org,v.projectId,true);const [existing]=await tx.select().from(packApplications).where(and(eq(packApplications.projectId,p.id),eq(packApplications.scopeKey,v.plan.scopeKey)));if(existing){if(existing.inputHash!==hash||existing.createdBy!==a.user.id)throw new WorkError('Un pack existe déjà pour cette occurrence ou campagne. Modifiez ses tâches.');return existing;}const b=await active(tx,p);const s=await scope(tx,p,v.plan.occurrenceId);if(v.expiresAt.getTime()<Date.now()||v.plan.projectRevision!==p.revision||v.plan.briefRevision!==b.revision||s.anchor!==v.plan.anchorDate)throw new WorkError('Cet aperçu a expiré ou le projet a changé. Préparez un nouvel aperçu.');if(new Set(rows.map(r=>r.key)).size!==rows.length||rows.some(r=>!v.plan.rows.some(x=>x.key===r.key)))throw new WorkError('Étapes invalides.');if(rows.some(r=>r.dueDate<todayIn(p.timezone)))reasonSchema.parse(lateReason);for(const row of rows){await candidate(tx,org,p.id,row.assigneeId);await candidate(tx,org,p.id,row.deputyId);if(row.assigneeId&&row.assigneeId===row.deputyId)throw new WorkError('Le suppléant doit être une autre personne.');}const [application]=await tx.insert(packApplications).values({projectId:p.id,scopeKey:s.key,previewId:v.id,template:v.plan.pack,version:v.plan.version,inputHash:hash,plan:rows,createdBy:a.user.id}).returning();await tx.insert(workTasks).values(rows.map(row=>({projectId:p.id,occurrenceId:v.plan.occurrenceId,scopeKey:s.key,taskKey:row.key,applicationId:application.id,title:row.title,description:row.description,format:row.format,dueDate:row.dueDate,originalDueDate:v.plan.rows.find(r=>r.key===row.key)!.originalDueDate,anchorDate:s.anchor,assigneeId:row.assigneeId,deputyId:row.deputyId,missionStatus:row.assigneeId?'proposed':'unassigned',createdBy:a.user.id})));await history(tx,a,p.id,'pack_applied',`Pack ${v.plan.pack} : ${rows.length} tâches. ${lateReason}`);return application;});},
 async createTask(a:Actor,org:string,id:string,occurrenceId:string|null,input:unknown,reason:string){const row=rowSchema.parse(input);z.uuid().parse(row.key);reason=actionComment(reason,false,'Tâche créée');return db.transaction(async tx=>{await lock(tx,org);const {p}=await guard(tx,a,org,id,true);await active(tx,p);const s=await scope(tx,p,occurrenceId);const [existing]=await tx.select().from(workTasks).where(and(eq(workTasks.projectId,id),eq(workTasks.scopeKey,s.key),eq(workTasks.taskKey,row.key)));if(existing){if(existing.createdBy!==a.user.id)throw new AccessError();if(existing.title!==row.title||existing.description!==row.description||existing.format!==row.format||existing.dueDate!==row.dueDate||existing.assigneeId!==row.assigneeId||existing.deputyId!==row.deputyId)throw new WorkError('Cette tâche a déjà été créée avec des valeurs différentes. Ouvrez-la pour la modifier.');return existing;}await candidate(tx,org,id,row.assigneeId);await candidate(tx,org,id,row.deputyId);if(row.assigneeId&&row.assigneeId===row.deputyId)throw new WorkError('Choisissez un autre suppléant.');const [t]=await tx.insert(workTasks).values({...row,taskKey:row.key,projectId:id,occurrenceId,scopeKey:s.key,anchorDate:s.anchor,originalDueDate:row.dueDate,missionStatus:row.assigneeId?'proposed':'unassigned',createdBy:a.user.id}).returning();await history(tx,a,id,'task_created',reason,t.id);return t;});},
 async mission(a:Actor,org:string,id:string,taskId:string,revision:number,accept:boolean,reason:string){reason=actionComment(reason,!accept,'Mission acceptée');return db.transaction(async tx=>{await lock(tx,org);const {p,m}=await guard(tx,a,org,id);await active(tx,p);const t=await task(tx,id,taskId,revision);await scope(tx,p,t.occurrenceId);if(t.assigneeId!==m.id||t.missionStatus!=='proposed')throw new WorkError('Seul le destinataire peut répondre à une proposition en cours.');await tx.update(workTasks).set({missionStatus:accept?'accepted':'refused',acceptedAt:accept?new Date():null,revision:t.revision+1}).where(eq(workTasks.id,t.id));await history(tx,a,id,accept?'mission_accepted':'mission_refused',reason,t.id);});},
 async status(a:Actor,org:string,id:string,taskId:string,revision:number,status:TaskStatus,reason:string){z.enum(['todo','doing','blocked','review','done']).parse(status);reason=actionComment(reason,status==='blocked','Avancement mis à jour : '+taskLabels[status]);return db.transaction(async tx=>{await lock(tx,org);const {p,m}=await guard(tx,a,org,id);await active(tx,p);const t=await task(tx,id,taskId,revision);const s=await scope(tx,p,t.occurrenceId);if(m.id!==t.assigneeId)await guard(tx,a,org,id,true);if(!taskTransitions[t.status as TaskStatus]?.includes(status))throw new WorkError('Transition de tâche indisponible.');if(['doing','review','done'].includes(status)){if(t.missionStatus!=='accepted')throw new WorkError('La mission doit d’abord être acceptée.');await candidate(tx,org,id,t.assigneeId);if(t.anchorDate!==s.anchor)throw new WorkError('La date du projet a changé : faites revoir l’échéance de la tâche.');const deps=await tx.select({status:workTasks.status}).from(taskDependencies).innerJoin(workTasks,eq(taskDependencies.dependsOnId,workTasks.id)).where(eq(taskDependencies.taskId,t.id));if(deps.some(d=>d.status!=='done'))throw new WorkError('Terminez les tâches préalables avant de poursuivre.');}await tx.update(workTasks).set({status,revision:t.revision+1}).where(eq(workTasks.id,t.id));await history(tx,a,id,`task_${status}`,reason,t.id);});},
 async edit(a:Actor,org:string,id:string,taskId:string,revision:number,input:unknown,priority:unknown,dependencies:string[],reason:string){const row=rowSchema.omit({key:true}).parse(input);const pr=z.enum(['normal','urgent']).parse(priority);const deps=z.array(z.uuid()).max(50).parse(dependencies);reason=actionComment(reason,false,'Tâche mise à jour');return db.transaction(async tx=>{await lock(tx,org);const {p}=await guard(tx,a,org,id,true);await active(tx,p);const t=await task(tx,id,taskId,revision);const s=await scope(tx,p,t.occurrenceId);await candidate(tx,org,id,row.assigneeId);await candidate(tx,org,id,row.deputyId);if(row.assigneeId&&row.assigneeId===row.deputyId)throw new WorkError('Choisissez un autre suppléant.');const others=await tx.select().from(workTasks).where(and(eq(workTasks.projectId,id),eq(workTasks.scopeKey,t.scopeKey)));if(deps.some(d=>!others.some(o=>o.id===d)))throw new WorkError('Les dépendances doivent appartenir à la même occurrence ou campagne.');const all=others.length?await tx.select().from(taskDependencies).where(inArray(taskDependencies.taskId,others.map(o=>o.id))):[];if(hasCycle([...all.filter(e=>e.taskId!==t.id),...deps.map(dependsOnId=>({taskId:t.id,dependsOnId}))]))throw new WorkError('Ces dépendances créeraient une boucle.');const changed=row.assigneeId!==t.assigneeId||t.missionStatus==='refused';await tx.update(workTasks).set({...row,priority:pr,anchorDate:s.anchor,revision:t.revision+1,...(changed?{missionStatus:row.assigneeId?'proposed':'unassigned',acceptedAt:null,status:'todo'}:{})}).where(eq(workTasks.id,t.id));await tx.delete(taskDependencies).where(eq(taskDependencies.taskId,t.id));if(deps.length)await tx.insert(taskDependencies).values([...new Set(deps)].map(dependsOnId=>({taskId:t.id,dependsOnId})));await history(tx,a,id,'task_edited',reason,t.id);});},
 async availability(a:Actor,org:string,input:unknown){const v=z.object({startDate:isoDate,endDate:isoDate,capacity:z.enum(['available','limited','unavailable']),note:z.string().trim().max(500)}).parse(input);if(v.endDate<v.startDate)throw new WorkError('La fin doit suivre le début.');return db.transaction(async tx=>{await lock(tx,org);const m=await membership(tx,a,org);await tx.insert(availabilities).values({...v,organizationId:org,memberId:m.id});});},
 async removeAvailability(a:Actor,org:string,id:string){z.uuid().parse(id);return db.transaction(async tx=>{await lock(tx,org);const m=await membership(tx,a,org);await tx.delete(availabilities).where(and(eq(availabilities.id,id),eq(availabilities.memberId,m.id),eq(availabilities.organizationId,org)));});}
 };
}
