import Link from 'next/link';
import { programmeContext,MissingSpace } from '../../../modules/programme/context';
import { workService } from '../../../modules/work/service';
import { AccessError } from '../../../modules/team/service';
import { taskLabels,taskTransitions,missionLabels,type TaskStatus } from '../../../modules/work/models';
import { WorkForm } from '../../../components/work-form';
import { TaskFields,Reason } from '../../../components/work-fields';
import { Badge } from '../../../components/ui/badge';
export const dynamic='force-dynamic';
export const metadata={title:'Fiche de tâche'};
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{organisation?:string;projet?:string}>}){const q=await searchParams;const {actor,db,org}=await programmeContext(q.organisation);if(!org||!q.projet)return <MissingSpace/>;let d;try{d=await workService(db).get(actor,org.id,q.projet);}catch(e){if(e instanceof AccessError)return <MissingSpace/>;throw e;}const taskId=(await params).id;const task=d.tasks.find(t=>t.id===taskId);if(!task)return <MissingSpace/>;const p=d.project;const event=d.events.find(e=>e.id===task.occurrenceId);const active=p.status==='preparation'&&d.brief.status==='accepted'&&(!task.occurrenceId||event?.status!=='cancelled');const changed=task.anchorDate!==(event?.startDate||p.startDate);const fields={organizationId:org.id,projectId:p.id,taskId:task.id,revision:task.revision};const person=(id:string|null)=>d.candidates.find(c=>c.member.id===id)?.name||(id?'Accès à revoir':'À désigner');return <><section className="page-title"><p className="eyebrow">{p.title}</p><h1>{task.title}</h1><div className="quick-actions"><Badge>{taskLabels[task.status as TaskStatus]}</Badge><Badge tone={task.missionStatus==='accepted'?'success':'info'}>{missionLabels[task.missionStatus as keyof typeof missionLabels]}</Badge></div><p>Échéance : {task.dueDate} · {p.timezone} · {task.format}</p><p>Mission : {person(task.assigneeId)} · Suppléant envisagé : {person(task.deputyId)}</p><p className="preserve-text">{task.description}</p></section><Link className="button secondary" href={`/projets/${p.id}/travail?organisation=${org.id}`}>Préparation et disponibilités</Link>{!active&&<p className="gentle-note">Travail suspendu : vérifiez la demande et l’état du projet ou de l’occurrence.</p>}{changed&&<p className="gentle-note">La date du projet a changé. Une personne autorisée doit revoir et enregistrer l’échéance avant la reprise.</p>}<p>Les missions et les tâches sont distinctes de la validation et de la publication des contenus.</p><nav className="quick-actions" aria-label="Ressources de la mission"><Link className="button secondary" href={`/medias?organisation=${org.id}`}>Consulter les rushs</Link><Link className="button secondary" href={`/livrables?organisation=${org.id}&projet=${p.id}`}>Livrables du projet</Link><Link className="button secondary" href={`/contenus?organisation=${org.id}&projet=${p.id}`}>Publications prévues</Link>{d.canEdit&&<Link className="button secondary" href={`/contenus/nouveau?organisation=${org.id}&projet=${p.id}`}>Préparer un contenu</Link>}</nav>
 {active&&task.assigneeId===d.member.id&&task.missionStatus==='proposed'&&<section className="card"><h2>Répondre à la proposition</h2><WorkForm key={`mission-${task.revision}`} fields={{...fields,operation:'mission'}}><Reason/><button name="answer" value="accept">Accepter la mission</button><button className="secondary" name="answer" value="refuse">Refuser la mission</button></WorkForm></section>}
 {active&&(d.canEdit||task.assigneeId===d.member.id)&&<section className="card section-spaced"><h2>Avancement</h2><WorkForm key={`status-${task.revision}`} fields={{...fields,operation:'status'}}><label>Nouvel état<select name="status">{taskTransitions[task.status as TaskStatus].map(s=><option key={s} value={s}>{taskLabels[s]}</option>)}</select></label><Reason/><button>Enregistrer l’avancement</button></WorkForm></section>}
 <section className="card section-spaced"><h2>Tâches préalables</h2><ul>{d.dependencies.filter(e=>e.taskId===task.id).map(e=><li key={e.id}>{d.tasks.find(t=>t.id===e.dependsOnId)?.title} · {taskLabels[d.tasks.find(t=>t.id===e.dependsOnId)?.status as TaskStatus]}</li>)}</ul></section>
 {active&&d.canEdit&&<section className="card section-spaced"><h2>Revoir la tâche ou proposer un remplacement</h2><p>Changer la personne relance une proposition et remet la tâche à faire. Le suppléant doit aussi accepter. Pour une urgence, indiquez les autres échéances à revoir dans le motif.</p><WorkForm key={`edit-${task.revision}`} fields={{...fields,operation:'edit'}}><TaskFields people={d.candidates} task={task}/><label>Priorité<select name="priority" defaultValue={task.priority}><option value="normal">Normale</option><option value="urgent">Urgente</option></select></label><fieldset><legend>Tâches préalables</legend>{d.tasks.filter(t=>t.id!==task.id&&t.scopeKey===task.scopeKey).map(t=><label className="check-label" key={t.id}><input type="checkbox" name="dependencies" value={t.id} defaultChecked={d.dependencies.some(e=>e.taskId===task.id&&e.dependsOnId===t.id)}/>{t.title}</label>)}</fieldset><Reason/>{changed&&<label className="check-label"><input type="checkbox" required/>J’ai revu l’échéance après le changement de date du projet.</label>}<button>Enregistrer la révision</button></WorkForm></section>}<section className="gentle-note"><h2>Historique</h2><ul>{d.history.filter(h=>h.taskId===task.id).map(h=><li key={h.id}>{h.createdAt.toLocaleDateString('fr-FR',{timeZone:p.timezone})} · {h.reason}</li>)}</ul></section></>;}
