import Link from 'next/link';
import { programmeContext, MissingSpace, SpaceNavigation } from '../../modules/programme/context';
import { programmeService } from '../../modules/programme/service';
import { Badge } from '../../components/ui/badge';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Projets' };
export default async function Page({ searchParams }: { searchParams: Promise<{ organisation?: string; type?: string; archives?: string }> }) {
  const query = await searchParams; const { actor, db, org, spaces } = await programmeContext(query.organisation); if (!org) return <MissingSpace/>;
  const service = programmeService(db); const list = (await service.list(actor, org.id)).filter(p => (!query.type || p.kind === query.type) && (query.archives === '1' ? p.status === 'archived' : p.status !== 'archived'));
  return <><section className="page-title"><p className="eyebrow">PROGRAMME · {org.name}</p><h1>Des projets qui prennent forme.</h1><p>Vos événements et campagnes enregistrés. Seuls les projets qui vous sont ouverts apparaissent ici.</p></section><SpaceNavigation spaces={spaces} selected={org.id} path="/projets"/><div className="section-head">{await service.canCreate(actor, org.id) && <Link className="button" href={`/projets/nouveau?organisation=${org.id}`}>Nouvel événement</Link>}<Link href={`/calendrier?organisation=${org.id}`}>Ouvrir le calendrier →</Link></div><form className="calendar-controls"><input type="hidden" name="organisation" value={org.id}/><label>Nature<select name="type" defaultValue={query.type || ''}><option value="">Tous les projets</option><option value="event">Événements</option><option value="campaign">Campagnes</option></select></label><label>Affichage<select name="archives" defaultValue={query.archives || '0'}><option value="0">Programme et annulations</option><option value="1">Archives</option></select></label><button>Filtrer</button></form><div className="project-grid">{list.map(p => <article className="card" key={p.id}><p className="eyebrow">{p.kind === 'event' ? 'Événement' : 'Campagne'}</p><h2><Link href={`/projets/${p.id}?organisation=${org.id}`}>{p.title}</Link></h2><p>{p.startDate} → {p.endDate} · {p.timezone}</p><Badge tone={p.status === 'cancelled' ? 'warning' : p.status === 'archived' ? 'neutral' : 'info'}>{p.status === 'cancelled' ? 'Annulé' : p.status === 'archived' ? 'Archivé' : 'Actif'}</Badge>{p.cadence !== 'none' && <p>{p.occurrenceCount} occurrences · {p.cadence === 'weekly' ? 'Hebdomadaire' : 'Mensuel'}</p>}</article>)}</div>{!list.length && <section className="card empty"><h2>Aucun projet dans cette vue.</h2><p>Créez un projet, adaptez les filtres ou demandez un accès nominatif à l’administrateur.</p></section>}</>;
}
