import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Pool} from 'pg';import {drizzle} from 'drizzle-orm/node-postgres';import {migrate} from 'drizzle-orm/node-postgres/migrator';import {eq,inArray} from 'drizzle-orm';
import * as core from '../../src/db/schema';import * as auth from '../../src/db/auth-schema';import * as team from '../../src/db/team-schema';import * as programme from '../../src/db/programme-schema';import * as work from '../../src/db/work-schema';import * as production from '../../src/db/production-schema';
import {teamService,type Actor} from '../../src/modules/team/service';import {programmeService} from '../../src/modules/programme/service';import {workService} from '../../src/modules/work/service';import {deletionService,processDeletions} from '../../src/modules/identity/deletion';
const url=process.env.TEST_DATABASE_URL;if(!url||!new URL(url).pathname.endsWith('_test')||url===process.env.DATABASE_URL)throw new Error('Base de test dédiée requise.');
test('Suppression : délai, annulation, transfert, isolement et purge des tâches/fichiers',async()=>{const pool=new Pool({connectionString:url}),db=drizzle(pool,{schema:{...core,...auth,...team,...programme,...work,...production}});const users:string[]=[],orgs:string[]=[];const removed:string[]=[];try{
 await migrate(db,{migrationsFolder:'./drizzle'});const ds=deletionService(db),ts=teamService(db);
 async function actor():Promise<Actor>{const id=randomUUID(),email=`${id}@test.invalid`;await db.insert(auth.user).values({id,email,emailVerified:true,name:'TEST deletion'});users.push(id);return {user:{id,email,emailVerified:true},session:{createdAt:new Date()}};}
 const a=await actor(),b=await actor(),c=await actor();const org=await ts.createOrganization(a,{name:'TEST deletion',timezone:'UTC'}),foreign=await ts.createOrganization(c,{name:'TEST preserved',timezone:'UTC'});orgs.push(org.id,foreign.id);
 const [mb]=await db.insert(team.members).values({organizationId:org.id,userId:b.user.id}).returning();
 await assert.rejects(ds.schedule({...a,session:{createdAt:new Date(0)}},'SUPPRIMER'));await assert.rejects(ds.schedule(a,'non'));
 const row=await ds.schedule(a,'SUPPRIMER');assert.ok(row.dueAt.getTime()>Date.now()+29*86400000);await processDeletions(db,async key=>{removed.push(key)});assert.equal((await db.select().from(core.organizations).where(eq(core.organizations.id,org.id))).length,1);
 await ds.cancel(a);assert.equal((await db.select().from(team.organizationDeletions).where(eq(team.organizationDeletions.organizationId,org.id))).length,0);
 await ds.schedule(a,'SUPPRIMER');await assert.rejects(ds.transfer(c,org.id,mb.id));await ds.transfer(a,org.id,mb.id);assert.equal((await ts.membership(b,org.id)).role,'admin');assert.equal((await ts.membership(a,org.id)).role,'member');
 await db.update(team.accountDeletions).set({dueAt:new Date(0)}).where(eq(team.accountDeletions.userId,a.user.id));await processDeletions(db,async()=>{});assert.equal((await db.select().from(auth.user).where(eq(auth.user.id,a.user.id)))[0].emailVerified,false);assert.equal((await db.select().from(core.organizations).where(eq(core.organizations.id,org.id))).length,1);
 const ps=programmeService(db),ws=workService(db);const p=await ps.create(b,org.id,{creationKey:randomUUID(),title:'TEST purge projet',kind:'event',eventType:'Rencontre',ministry:'',location:'Salle',practicalInfo:'Libre',ownerId:'',validatorId:'',deputyId:'',decisionMakerId:'',communicationLevel:'standard',timezone:'UTC',startDate:'2090-09-15',endDate:'2090-09-15',allDay:true,startTime:null,endTime:null,cadence:'none',occurrenceCount:1,objective:'Préparer une rencontre',audience:'Bénévoles',message:'Invitation à la rencontre',resources:'',usefulDate:''});
 await ws.decide(b,org.id,p.id,1,'accepted','Demande confirmée');const d=await ws.get(b,org.id,p.id);await ws.createTask(b,org.id,p.id,d.events[0].id,{key:randomUUID(),title:'TEST tâche',description:'',format:'Photo',dueDate:'2090-09-15',assigneeId:null,deputyId:null},'Tâche de test');
 const storageKey=`test/${randomUUID()}`;await db.insert(production.media).values({organizationId:org.id,projectId:p.id,createdBy:b.user.id,uploadKey:randomUUID(),name:'TEST.jpg',mime:'image/jpeg',size:10,sha256:'test',category:'photo',storageKey});
 await ds.schedule(b,'SUPPRIMER');await db.update(team.organizationDeletions).set({dueAt:new Date(0)}).where(eq(team.organizationDeletions.organizationId,org.id));await db.update(team.accountDeletions).set({dueAt:new Date(0)}).where(eq(team.accountDeletions.userId,b.user.id));
 await processDeletions(db,async()=>{throw new Error('Storage unavailable')});assert.equal((await db.select().from(core.organizations).where(eq(core.organizations.id,org.id))).length,0);assert.equal((await db.select().from(team.erasedFiles).where(eq(team.erasedFiles.key,storageKey))).length,1);
 await processDeletions(db,async key=>{removed.push(key)});assert.ok(removed.includes(storageKey));assert.equal((await db.select().from(core.organizations).where(eq(core.organizations.id,foreign.id))).length,1);
 }finally{await db.delete(team.organizationDeletions).where(inArray(team.organizationDeletions.organizationId,orgs));await db.delete(team.accountDeletions).where(inArray(team.accountDeletions.userId,users));await db.delete(team.accessAudit).where(inArray(team.accessAudit.organizationId,orgs));await db.delete(team.members).where(inArray(team.members.organizationId,orgs));await db.delete(core.organizations).where(inArray(core.organizations.id,orgs));await db.delete(auth.user).where(inArray(auth.user.id,users));await pool.end();}
});
