import {contentAssets} from '../../src/modules/production/content-assets';
import {test} from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {Pool} from 'pg';import {drizzle} from 'drizzle-orm/node-postgres';import {migrate} from 'drizzle-orm/node-postgres/migrator';import {eq,inArray} from 'drizzle-orm';
import * as core from '../../src/db/schema';import * as auth from '../../src/db/auth-schema';import * as team from '../../src/db/team-schema';import * as programme from '../../src/db/programme-schema';import * as work from '../../src/db/work-schema';import * as production from '../../src/db/production-schema';
import {teamService,type Actor} from '../../src/modules/team/service';import {programmeService} from '../../src/modules/programme/service';import {directDriveService} from '../../src/modules/integrations/direct-drive/service';import {seal} from '../../src/modules/integrations/direct-drive/google';
const url=process.env.TEST_DATABASE_URL;if(!url||!new URL(url).pathname.endsWith('_test')||url===process.env.DATABASE_URL)throw new Error('Base de test dédiée requise');
test('Drive direct : isolation, gros fichier déclaré, reprise, confirmation et classement idempotent',async()=>{
const pool=new Pool({connectionString:url});const db=drizzle(pool,{schema:{...core,...auth,...team,...programme,...work,...production}});const orgs:string[]=[],users:string[]=[],oldFetch=globalThis.fetch;const oldUrl=process.env.BETTER_AUTH_URL;process.env.BETTER_AUTH_URL='https://com-eternel.vercel.app';const oldSecret=process.env.BETTER_AUTH_SECRET;process.env.BETTER_AUTH_SECRET='test-only-secret-not-a-real-credential-00000000';
try{await migrate(db,{migrationsFolder:'./drizzle'});async function actor():Promise<Actor>{const id=randomUUID(),email=`${id}@test.invalid`;await db.insert(auth.user).values({id,email,emailVerified:true,name:'Test direct Drive'});users.push(id);return {user:{id,email,emailVerified:true},session:{createdAt:new Date()}};}
const a=await actor(),b=await actor(),member=await actor();const ts=teamService(db),ps=programmeService(db);const oa=await ts.createOrganization(a,{name:'TEST association A',timezone:'UTC'}),ob=await ts.createOrganization(b,{name:'TEST association B',timezone:'UTC'});orgs.push(oa.id,ob.id);await db.insert(team.members).values({organizationId:oa.id,userId:member.user.id,role:'member',permissions:[],professions:[]});
const values={creationKey:randomUUID(),title:'Événement A',kind:'event',eventType:'Rencontre',ministry:'',location:'Salle',practicalInfo:'',ownerId:'',validatorId:'',deputyId:'',decisionMakerId:'',communicationLevel:'essential',timezone:'UTC',startDate:'2020-09-24',endDate:'2020-09-24',allDay:true,startTime:null,endTime:null,cadence:'none',occurrenceCount:1,objective:'Préparer une rencontre',audience:'Membres',message:'Invitation',resources:'',usefulDate:''};const p=await ps.create(a,oa.id,values);const ev=(await ps.get(a,oa.id,p.id)).events[0];
await db.insert(production.driveConnections).values({organizationId:oa.id,connectedBy:a.user.id,googleSubject:'google-a',googleEmail:'a@test.invalid',refreshToken:seal('refresh-a',`drive:${oa.id}`),rootId:'root-a',inboxId:'inbox-a'});
const files=new Map<string,any>(),folders=new Map<string,string>();let next=0,moves=0;const seenTokens:string[]=[];
globalThis.fetch=(async(raw:any,init:any={})=>{const u=new URL(String(raw));const headers=new Headers(init.headers);if(u.hostname==='oauth2.googleapis.com'){assert.equal(new URLSearchParams(init.body).get('refresh_token'),'refresh-a');return Response.json({access_token:'access-a'});}seenTokens.push(headers.get('authorization')||'');if(u.pathname.includes('generateIds'))return Response.json({ids:[`file-${++next}`]});if(u.pathname.startsWith('/upload/')){if(init.method==='POST'){const body=JSON.parse(init.body);files.set(body.id,{...body,size:String(headers.get('x-upload-content-length')),sha256Checksum:'a'.repeat(64),trashed:false});return new Response(null,{status:200,headers:{location:`https://www.googleapis.com/upload/drive/v3/files?upload_id=${body.id}`}});}return new Response(null,{status:308,headers:{range:'bytes=0-8388607'}});}if(u.pathname.endsWith('/files')){if(init.method==='POST'){const body=JSON.parse(init.body),id=`folder-${++next}`;folders.set(body.appProperties.cometernelFolder+':'+body.parents[0],id);return Response.json({id});}const q=u.searchParams.get('q')!;const key=q.match(/value='([^']+)'/)![1],parent=q.match(/and '([^']+)' in parents/)![1];const id=folders.get(key+':'+parent);return Response.json({files:id?[{id}]:[]});}const id=u.pathname.split('/').pop()!;if(id==='root-a'){if(init.method==='PATCH'){assert.equal(JSON.parse(init.body).name,'Multimédia ComÉternel');return Response.json({id});}return Response.json({id,name:'Ancien dossier',mimeType:'application/vnd.google-apps.folder',appProperties:{cometernelOrg:oa.id,cometernelFolder:`root:${oa.id}`}});}const f=files.get(id);if(!f)return new Response(null,{status:404});if(init.method==='PATCH'){moves++;f.parents=[u.searchParams.get('addParents')];}return Response.json(f);}) as typeof fetch;
const service=directDriveService(db),who={actor:member,org:oa.id};const input={projectId:p.id,occurrenceId:ev.id,uploadKey:randomUUID(),name:'video-1Go.mp4',mime:'video/mp4',size:1024**3,sha256:'a'.repeat(64),category:'rush'};
await assert.rejects(service.begin({actor:b,org:oa.id},input));await assert.rejects(service.begin({actor:member,org:ob.id},input));await assert.rejects(service.begin(who,{...input,category:'deliverable'}));
const started=await service.begin(who,input);assert.ok(started.uri?.startsWith('https://www.googleapis.com/upload/'));const again=await service.begin(who,input);assert.equal(again.id,started.id);assert.equal(again.uri,started.uri);assert.equal(files.size,1);
assert.equal((await service.status(who,started.id)).received,8388608);await assert.rejects(service.status({actor:b,org:ob.id},started.id));await assert.rejects(service.complete({actor:a,org:oa.id},started.id));
const object=[...files.values()][0];object.sha256Checksum='b'.repeat(64);await assert.rejects(service.complete(who,started.id));object.sha256Checksum='a'.repeat(64);
// If completion was lost and the resumable URL expires, recover the existing object.
await db.update(production.directUploads).set({sessionUri:null,sessionExpiresAt:null}).where(eq(production.directUploads.mediaId,started.id));
assert.equal((await service.begin(who,input)).status,'ready');assert.equal(files.size,1);
await service.complete(who,started.id);
const jobs=await Promise.all([service.claim(),service.claim()]);assert.equal(jobs.filter(j=>j.job).length,1);const job=jobs.find(j=>j.job)!.job!;assert.equal(job.organizationId,oa.id);await assert.rejects(service.classify(job.id,randomUUID()));await service.classify(job.id,job.leaseId);await service.classify(job.id,job.leaseId);assert.equal(moves,1);assert.equal((await service.claim()).job,null);assert.equal(folders.size,4);assert.ok([...folders.keys()].some(k=>k.startsWith('year:2020')));assert.ok([...folders.keys()].some(k=>k.startsWith('category:rush')));assert.ok([...folders.keys()].some(k=>k.startsWith('type:video')));assert.ok(seenTokens.every(t=>t===''||t==='Bearer access-a'));assert.equal((await service.begin(who,input)).status,'classified');
const [asset]=await db.select().from(production.media).where(eq(production.media.id,started.id));
assert.equal((await contentAssets(db,[asset]))[0].contentReady,false,'Les rushs ne deviennent pas des livrables');
await db.update(production.media).set({category:'deliverable'}).where(eq(production.media.id,asset.id));
const [deliverable]=await db.select().from(production.media).where(eq(production.media.id,asset.id));
assert.equal((await contentAssets(db,[deliverable]))[0].contentReady,true,'Un fichier Drive reçu est sélectionnable');
assert.equal((await contentAssets(db,[{...deliverable,state:'quarantine'}]))[0].contentReady,false);
assert.equal((await contentAssets(db,[{...deliverable,received:0}]))[0].contentReady,false);
assert.equal((await contentAssets(db,[{...deliverable,organizationId:ob.id}]))[0].contentReady,false);

}finally{globalThis.fetch=oldFetch;process.env.BETTER_AUTH_URL=oldUrl;if(oldSecret)process.env.BETTER_AUTH_SECRET=oldSecret;else delete process.env.BETTER_AUTH_SECRET;
if(orgs.length){await db.delete(production.directUploads).where(inArray(production.directUploads.organizationId,orgs));await db.delete(production.media).where(inArray(production.media.organizationId,orgs));await db.delete(production.driveConnections).where(inArray(production.driveConnections.organizationId,orgs));const ps=await db.select().from(programme.projects).where(inArray(programme.projects.organizationId,orgs));const ids=ps.map(p=>p.id);if(ids.length){await db.delete(team.projectGrants).where(inArray(team.projectGrants.projectId,ids));await db.delete(programme.programmeChanges).where(inArray(programme.programmeChanges.projectId,ids));await db.delete(programme.occurrences).where(inArray(programme.occurrences.projectId,ids));await db.delete(programme.briefs).where(inArray(programme.briefs.projectId,ids));await db.delete(programme.projects).where(inArray(programme.projects.id,ids));}await db.delete(team.accessAudit).where(inArray(team.accessAudit.organizationId,orgs));await db.delete(team.members).where(inArray(team.members.organizationId,orgs));await db.delete(core.organizations).where(inArray(core.organizations.id,orgs));}if(users.length)await db.delete(auth.user).where(inArray(auth.user.id,users));await pool.end();}
});
