import { pgTable, uuid, text, integer, bigint, timestamp, jsonb, date, uniqueIndex, boolean, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { organizations } from './schema';
import { projects, occurrences } from './programme-schema';
import { user } from './auth-schema';
const time=()=>timestamp('created_at',{withTimezone:true}).defaultNow().notNull();
export const collections=pgTable('collections',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id),projectId:uuid('project_id').notNull().references(()=>projects.id),occurrenceId:uuid('occurrence_id').references(()=>occurrences.id),tokenHash:text('token_hash').notNull().unique(),codeHash:text('code_hash'),title:text('title').notNull(),instructions:text('instructions').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull(),revokedAt:timestamp('revoked_at',{withTimezone:true}),maxFiles:integer('max_files').notNull(),maxBytes:bigint('max_bytes',{mode:'number'}).notNull(),allowProposal:boolean('allow_proposal').default(false).notNull(),createdBy:text('created_by').notNull().references(()=>user.id),createdAt:time()});
export const media=pgTable('media',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id),projectId:uuid('project_id').notNull().references(()=>projects.id),occurrenceId:uuid('occurrence_id').references(()=>occurrences.id),collectionId:uuid('collection_id').references(()=>collections.id),createdBy:text('created_by').references(()=>user.id),uploadKey:text('upload_key').notNull(),name:text('name').notNull(),mime:text('mime').notNull(),size:bigint('size',{mode:'number'}).notNull(),received:bigint('received',{mode:'number'}).default(0).notNull(),sha256:text('sha256').notNull(),category:text('category').notNull(),state:text('state').notNull().default('uploading'),storageKey:text('storage_key'),reviewReason:text('review_reason'),reviewedBy:text('reviewed_by').references(()=>user.id),proposalTitle:text('proposal_title'),proposalDate:date('proposal_date'),proposalState:text('proposal_state'),guestName:text('guest_name').notNull().default(''),note:text('note').notNull().default(''),revision:integer('revision').notNull().default(1),rights:jsonb('rights').$type<{author:string;people:string;music:string;minors:string;channels:string[];evidence:string;reviewDate:string;reviewer:string;withdrawn:boolean}>(),createdAt:time()},t=>[uniqueIndex('media_upload_identity').on(t.organizationId,t.uploadKey),check('media_size',sql`${t.size}>0 and ${t.received}>=0 and ${t.received}<=${t.size}`)]);
export const mediaParts=pgTable('media_parts',{id:uuid('id').defaultRandom().primaryKey(),mediaId:uuid('media_id').notNull().references(()=>media.id),offset:bigint('offset',{mode:'number'}).notNull(),size:integer('size').notNull(),hash:text('hash').notNull(),key:text('key').notNull()},t=>[uniqueIndex('media_part_offset').on(t.mediaId,t.offset)]);
export const contents=pgTable('contents',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id),projectId:uuid('project_id').notNull().references(()=>projects.id),occurrenceId:uuid('occurrence_id').references(()=>occurrences.id),title:text('title').notNull(),channel:text('channel').notNull(),format:text('format').notNull(),plannedDate:date('planned_date').notNull(),status:text('status').default('draft').notNull(),currentVersion:integer('current_version').default(1).notNull(),revision:integer('revision').default(1).notNull(),creationKey:uuid('creation_key').notNull(),createdBy:text('created_by').notNull().references(()=>user.id),createdAt:time()},t=>[uniqueIndex('content_creation').on(t.organizationId,t.creationKey)]);
export const contentVersions=pgTable('content_versions',{id:uuid('id').defaultRandom().primaryKey(),contentId:uuid('content_id').notNull().references(()=>contents.id),number:integer('number').notNull(),caption:text('caption').notNull(),brief:text('brief').notNull(),practicalUrl:text('practical_url').notNull(),creationUrl:text('creation_url').notNull(),reference:text('reference').notNull(),mediaIds:jsonb('media_ids').$type<string[]>().notNull(),channel:text('channel').notNull(),rights:jsonb('rights').$type<{author:string;people:string;music:string;minors:string;channels:string[];evidence:string;reviewDate:string;reviewer:string;withdrawn:boolean}>(),createdBy:text('created_by').notNull().references(()=>user.id),createdAt:time()},t=>[uniqueIndex('content_version_number').on(t.contentId,t.number)]);
export const decisions=pgTable('content_decisions',{id:uuid('id').defaultRandom().primaryKey(),contentId:uuid('content_id').notNull().references(()=>contents.id),versionId:uuid('version_id').notNull().references(()=>contentVersions.id),actorId:text('actor_id').notNull().references(()=>user.id),decision:text('decision').notNull(),reason:text('reason').notNull(),fingerprint:text('fingerprint').notNull(),createdAt:time()});
export const publications=pgTable('publications',{id:uuid('id').defaultRandom().primaryKey(),contentId:uuid('content_id').notNull().references(()=>contents.id),versionId:uuid('version_id').notNull().references(()=>contentVersions.id),fingerprint:text('fingerprint').notNull(),status:text('status').notNull().default('prepared'),proof:text('proof'),publishedAt:timestamp('published_at',{withTimezone:true}),responseOwner:text('response_owner').notNull(),actorId:text('actor_id').notNull().references(()=>user.id),createdAt:time()},t=>[uniqueIndex('publication_version').on(t.versionId)]);
export const productionHistory=pgTable('production_history',{id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id),projectId:uuid('project_id').notNull().references(()=>projects.id),actorId:text('actor_id').references(()=>user.id),action:text('action').notNull(),reason:text('reason').notNull(),createdAt:time()});
export const requestLimits=pgTable('request_limits',{key:text('key').primaryKey(),count:integer('count').notNull(),expiresAt:timestamp('expires_at',{withTimezone:true}).notNull()});

export const driveTransfers=pgTable('drive_transfers',{
 id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id),mediaId:uuid('media_id').notNull().references(()=>media.id),createdBy:text('created_by').notNull().references(()=>user.id),folderId:text('folder_id').notNull(),status:text('status').notNull().default('queued'),attempts:integer('attempts').notNull().default(0),requestId:text('request_id'),leaseId:uuid('lease_id'),leaseUntil:timestamp('lease_until',{withTimezone:true}),driveFileId:text('drive_file_id'),errorCode:text('error_code'),receipt:jsonb('receipt').$type<{id:string;size:string;sha256Checksum:string;parents:string[];trashed:boolean;mimeType?:string;appProperties:{cometernelJob:string}}>(),createdAt:time(),completedAt:timestamp('completed_at',{withTimezone:true})
},t=>[uniqueIndex('drive_transfer_destination').on(t.organizationId,t.mediaId,t.folderId),uniqueIndex('drive_claim_request').on(t.organizationId,t.requestId),check('drive_transfer_status',sql`${t.status} in ('queued','running','succeeded','failed','suspended')`),check('drive_transfer_attempts',sql`${t.attempts} >= 0`)]);

export const driveConnections=pgTable('drive_connections',{
 id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),connectedBy:text('connected_by').notNull().references(()=>user.id),googleSubject:text('google_subject').notNull(),googleEmail:text('google_email').notNull(),refreshToken:text('refresh_token').notNull(),rootId:text('root_id').notNull(),inboxId:text('inbox_id').notNull(),status:text('status').default('connected').notNull(),createdAt:time()
},t=>[uniqueIndex('drive_connection_org').on(t.organizationId)]);
export const directUploads=pgTable('direct_drive_uploads',{
 id:uuid('id').defaultRandom().primaryKey(),mediaId:uuid('media_id').notNull().references(()=>media.id,{onDelete:'cascade'}),organizationId:uuid('organization_id').notNull().references(()=>organizations.id,{onDelete:'cascade'}),connectionId:uuid('connection_id').notNull().references(()=>driveConnections.id),driveFileId:text('drive_file_id').notNull(),sessionUri:text('session_uri'),sessionExpiresAt:timestamp('session_expires_at',{withTimezone:true}),status:text('status').default('uploading').notNull(),leaseId:uuid('lease_id'),leaseUntil:timestamp('lease_until',{withTimezone:true}),attempts:integer('attempts').default(0).notNull(),errorCode:text('error_code'),folderId:text('folder_id'),completedAt:timestamp('completed_at',{withTimezone:true}),createdAt:time()
},t=>[uniqueIndex('direct_upload_media').on(t.mediaId),uniqueIndex('direct_upload_file').on(t.driveFileId)]);
