import { pgTable, uuid, text, date, timestamp, integer, boolean, uniqueIndex, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { organizations } from './schema';
import { members } from './team-schema';
import { user } from './auth-schema';
export const projects = pgTable('projects', {
  id: uuid('id').defaultRandom().primaryKey(), organizationId: uuid('organization_id').notNull().references(() => organizations.id), createdBy: text('created_by').notNull().references(() => user.id), creationKey: uuid('creation_key').notNull(), inputHash: text('input_hash').notNull(),
  title: text('title').notNull(), kind: text('kind').notNull(), eventType: text('event_type').notNull(), ministry: text('ministry').notNull().default(''), location: text('location').notNull().default(''), practicalInfo: text('practical_info').notNull().default(''),
  ownerId: uuid('owner_id').references(() => members.id), validatorId: uuid('validator_id').references(() => members.id), deputyId: uuid('deputy_id').references(() => members.id), communicationLevel: text('communication_level').notNull(),
  timezone: text('timezone').notNull(), startDate: date('start_date').notNull(), endDate: date('end_date').notNull(), allDay: boolean('all_day').notNull(), startTime: text('start_time'), endTime: text('end_time'), cadence: text('cadence').notNull(), occurrenceCount: integer('occurrence_count').notNull(),
  status: text('status').notNull().default('preparation'), revision: integer('revision').notNull().default(1), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull(),
}, t => [uniqueIndex('project_creation_key').on(t.organizationId, t.creationKey), check('project_kind', sql`${t.kind} in ('event','campaign')`), check('project_status', sql`${t.status} in ('preparation','cancelled','archived')`), check('project_period', sql`${t.endDate} >= ${t.startDate}`), check('project_cadence', sql`${t.cadence} in ('none','weekly','monthly')`), check('project_count', sql`${t.occurrenceCount} between 1 and 104`)]);
export const briefs = pgTable('project_briefs', { id: uuid('id').defaultRandom().primaryKey(), organizationId: uuid('organization_id').notNull().references(() => organizations.id), projectId: uuid('project_id').notNull().references(() => projects.id).unique(), objective: text('objective').notNull(), audience: text('audience').notNull(), message: text('message').notNull(), resources: text('resources').notNull().default(''), usefulDate: date('useful_date'), decisionMakerId: uuid('decision_maker_id').references(() => members.id), status: text('status').notNull().default('received'), revision: integer('revision').notNull().default(1), decisionReason: text('decision_reason'), decidedBy: text('decided_by').references(() => user.id), decidedAt: timestamp('decided_at', { withTimezone: true }) });
export const occurrences = pgTable('occurrences', {
  id: uuid('id').defaultRandom().primaryKey(), projectId: uuid('project_id').notNull().references(() => projects.id), sequence: integer('sequence').notNull(), originalStartDate: date('original_start_date').notNull(), startDate: date('start_date').notNull(), endDate: date('end_date').notNull(), startAt: timestamp('start_at', { withTimezone: true }), endAt: timestamp('end_at', { withTimezone: true }), status: text('status').notNull().default('scheduled'), isException: boolean('is_exception').notNull().default(false), changeReason: text('change_reason'),
}, t => [uniqueIndex('occurrence_project_sequence').on(t.projectId, t.sequence), check('occurrence_status', sql`${t.status} in ('scheduled','rescheduled','cancelled')`), check('occurrence_period', sql`${t.endDate} >= ${t.startDate}`), check('occurrence_instants', sql`(${t.startAt} is null and ${t.endAt} is null) or (${t.startAt} is not null and ${t.endAt} > ${t.startAt})`)]);
export const programmeChanges = pgTable('programme_changes', { id: uuid('id').defaultRandom().primaryKey(), projectId: uuid('project_id').notNull().references(() => projects.id), occurrenceId: uuid('occurrence_id').references(() => occurrences.id), actorId: text('actor_id').notNull().references(() => user.id), action: text('action').notNull(), reason: text('reason').notNull(), createdAt: timestamp('created_at', { withTimezone: true }).defaultNow().notNull() });
export const liturgicalDates = pgTable('liturgical_dates', { id: uuid('id').defaultRandom().primaryKey(), organizationId: uuid('organization_id').notNull().references(() => organizations.id), title: text('title').notNull(), date: date('date').notNull(), tradition: text('tradition').notNull(), localCalendar: text('local_calendar').notNull(), source: text('source').notNull(), verifiedBy: text('verified_by').references(() => user.id), verifiedAt: timestamp('verified_at', { withTimezone: true }), revision: integer('revision').notNull().default(1) });
