import { pgTable, uuid, text, date, timestamp, integer, jsonb, uniqueIndex, check } from 'drizzle-orm/pg-core';
import { sql } from 'drizzle-orm';
import { organizations } from './schema';
import { user } from './auth-schema';
import { members } from './team-schema';
import { projects, occurrences } from './programme-schema';
import type { PackPlan } from '../modules/work/models';
export const packPreviews = pgTable('pack_previews', { id: uuid('id').defaultRandom().primaryKey(), projectId: uuid('project_id').notNull().references(() => projects.id), createdBy: text('created_by').notNull().references(() => user.id), plan: jsonb('plan').$type<PackPlan>().notNull(), expiresAt: timestamp('expires_at',{ withTimezone:true }).notNull() });
export const packApplications = pgTable('pack_applications', { id: uuid('id').defaultRandom().primaryKey(), projectId: uuid('project_id').notNull().references(() => projects.id), scopeKey: text('scope_key').notNull(), previewId: uuid('preview_id').notNull().references(() => packPreviews.id), template: text('template').notNull(), version: integer('version').notNull(), inputHash: text('input_hash').notNull(), plan: jsonb('plan').notNull(), createdBy: text('created_by').notNull().references(() => user.id), createdAt: timestamp('created_at',{ withTimezone:true }).defaultNow().notNull() }, t=>[uniqueIndex('one_pack_per_scope').on(t.projectId,t.scopeKey)]);
export const workTasks = pgTable('work_tasks', {
  id: uuid('id').defaultRandom().primaryKey(), projectId: uuid('project_id').notNull().references(() => projects.id), occurrenceId: uuid('occurrence_id').references(() => occurrences.id), scopeKey: text('scope_key').notNull(), taskKey: text('task_key').notNull(), applicationId: uuid('application_id').references(() => packApplications.id), title: text('title').notNull(), description: text('description').notNull().default(''), format: text('format').notNull(), priority: text('priority').notNull().default('normal'), dueDate: date('due_date').notNull(), originalDueDate: date('original_due_date').notNull(), anchorDate: date('anchor_date').notNull(), status: text('status').notNull().default('todo'), assigneeId: uuid('assignee_id').references(() => members.id), deputyId: uuid('deputy_id').references(() => members.id), missionStatus: text('mission_status').notNull().default('unassigned'), acceptedAt: timestamp('accepted_at',{ withTimezone:true }), revision: integer('revision').notNull().default(1), resources: jsonb('resources').$type<{ label:string; url:string }[]>().notNull().default([]), createdBy: text('created_by').notNull().references(() => user.id), createdAt: timestamp('created_at',{ withTimezone:true }).defaultNow().notNull(),
},t=>[uniqueIndex('work_task_scope_key').on(t.projectId,t.scopeKey,t.taskKey),check('work_task_status',sql`${t.status} in ('todo','doing','blocked','review','done')`),check('work_mission_status',sql`${t.missionStatus} in ('unassigned','proposed','accepted','refused')`),check('work_priority',sql`${t.priority} in ('normal','urgent')`),check('work_assignment_state',sql`(${t.assigneeId} is null and ${t.missionStatus}='unassigned' and ${t.acceptedAt} is null) or (${t.assigneeId} is not null and ${t.missionStatus} in ('proposed','refused') and ${t.acceptedAt} is null) or (${t.assigneeId} is not null and ${t.missionStatus}='accepted' and ${t.acceptedAt} is not null)`)]);
export const taskDependencies = pgTable('task_dependencies', { id:uuid('id').defaultRandom().primaryKey(), taskId:uuid('task_id').notNull().references(()=>workTasks.id), dependsOnId:uuid('depends_on_id').notNull().references(()=>workTasks.id) },t=>[uniqueIndex('task_dependency_unique').on(t.taskId,t.dependsOnId),check('no_self_dependency',sql`${t.taskId}<>${t.dependsOnId}`)]);
export const workHistory = pgTable('work_history',{ id:uuid('id').defaultRandom().primaryKey(),projectId:uuid('project_id').notNull().references(()=>projects.id),taskId:uuid('task_id').references(()=>workTasks.id),actorId:text('actor_id').notNull().references(()=>user.id),action:text('action').notNull(),reason:text('reason').notNull(),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull() });
export const availabilities = pgTable('availabilities',{ id:uuid('id').defaultRandom().primaryKey(),organizationId:uuid('organization_id').notNull().references(()=>organizations.id),memberId:uuid('member_id').notNull().references(()=>members.id),startDate:date('start_date').notNull(),endDate:date('end_date').notNull(),capacity:text('capacity').notNull(),note:text('note').notNull().default(''),createdAt:timestamp('created_at',{withTimezone:true}).defaultNow().notNull() },t=>[check('availability_dates',sql`${t.endDate}>=${t.startDate}`),check('availability_capacity',sql`${t.capacity} in ('available','limited','unavailable')`)]);
