import {programmeContext,MissingSpace} from '../../modules/programme/context';
import {programmeService} from '../../modules/programme/service';
import {mediaService} from '../../modules/production/media-service';
import {ProductionForm} from '../../components/production-form';
export const dynamic='force-dynamic';export const metadata={title:'Inviter à déposer'};
export default async function Page({searchParams}:{searchParams:Promise<{organisation?:string}>}) {
 const {actor,db,org}=await programmeContext((await searchParams).organisation);if(!org)return <MissingSpace/>;
 const service=programmeService(db),ms=mediaService(db),ps=await service.list(actor,org.id),entries=[];
 for(const p of ps.filter(p=>p.kind==='event'&&p.status==='preparation')){const d=await service.get(actor,org.id,p.id);if(d.canEdit&&d.events.some(e=>e.status!=='cancelled'))entries.push({...d,collections:await ms.listCollections(actor,org.id,p.id)});}
 const expires=new Date(Date.now()+30*86400000).toISOString().slice(0,10);
 return <><section className="page-title"><h1>Inviter à déposer des photos et vidéos</h1><p>Choisissez l’événement, créez le lien et partagez-le. L’invité arrive directement sur le dépôt de cet événement, sans compte ni connexion Google.</p></section>{!entries.length&&<section className="card"><p>Créez d’abord un événement ou demandez à votre administrateur de vous autoriser à préparer son lien de dépôt.</p></section>}{entries.map(d=><section className="card section-spaced" key={d.project.id}><h2>{d.project.title}</h2><ProductionForm fields={{operation:'collection',organizationId:org.id,projectId:d.project.id,title:d.project.title,allowProposal:''}}><label>Date de l’événement<select name="occurrenceId" required>{d.events.filter(e=>e.status!=='cancelled').map(e=><option key={e.id} value={e.id}>{e.startDate}</option>)}</select></label><label>Message pour les invités<textarea name="instructions" minLength={5} maxLength={2000} defaultValue="Déposez ici les photos et vidéos que vous avez prises pendant cet événement." required/></label><details><summary>Durée du lien et limites de dépôt</summary><label>Lien valable jusqu’au (UTC)<input name="expiresAt" type="date" defaultValue={expires} required/></label><div className="field-grid"><label>Nombre maximal de fichiers pour ce lien<input name="maxFiles" type="number" min={1} max={100} defaultValue={100} required/></label><label>Volume total maximal en Mo<input name="maxMB" type="number" min={1} max={1024} defaultValue={1024} required/></label></div><p className="hint">Par défaut : 30 jours, 100 fichiers et 1 Go au total pour ce lien. Vous pouvez créer un autre lien si nécessaire.</p><label>Code de protection (facultatif)<input name="code" autoComplete="off" maxLength={100}/></label></details><p>Le dépôt ouvre au début de l’événement. Les invités ne voient pas les fichiers des autres.</p><button>Créer le lien à partager</button></ProductionForm>{!!d.collections.length&&<details className="section-spaced"><summary>Liens déjà créés ({d.collections.length})</summary><ul className="item-list">{d.collections.map(c=><li key={c.id}>{c.title} · Jusqu’au {c.expiresAt.toISOString().slice(0,10)} · {c.revokedAt?'Désactivé':c.expiresAt<new Date()?'Expiré':'Actif'}{!c.revokedAt&&<ProductionForm fields={{operation:'revoke',organizationId:org.id,id:c.id}}><button className="secondary">Désactiver ce lien</button></ProductionForm>}</li>)}</ul></details>}</section>)}</>;
}
