import Link from 'next/link';
import { requireSession } from '../../modules/identity/session';
import { teamService, AccessError } from '../../modules/team/service';
import { getDb } from '../../db/client';
import { Badge } from '../../components/ui/badge';
import { TeamForm } from './team-form';
import { profiles, type Profile } from '../../modules/preview/data';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Équipe' };
export default async function Page({ searchParams }: { searchParams: Promise<{ organisation?: string }> }) {
  const actor = await requireSession(); const service = teamService(getDb()); const spaces = await service.listOrganizations(actor); const requested = (await searchParams).organisation; const org = requested ? spaces.find(s => s.id === requested) : spaces[0];
  if (!org) return <section className="card"><h1>{requested ? 'Espace indisponible.' : 'Votre équipe commence ici.'}</h1><p>{requested ? 'Ce compte ne peut pas ouvrir cet espace.' : 'Créez votre espace ou acceptez une invitation pour retrouver votre équipe.'}</p><Link href="/compte">Mon compte →</Link></section>;
  let people; let invites;
  try { people = await service.listMembers(actor, org.id); invites = org.role === 'admin' ? await service.listInvitations(actor, org.id) : []; }
  catch (error) { if (error instanceof AccessError) return <section className="card"><h1>Accès indisponible.</h1><Link href="/compte">Revenir à mon compte</Link></section>; throw error; }
  return <><section className="page-title"><p className="eyebrow">ÉQUIPE · DONNÉES DE VOTRE ESPACE</p><h1>{org.name}</h1><p>Métiers et accès de votre équipe. Les exemples fictifs de l’accueil n’affectent pas cette page.</p></section><nav className="quick-actions" aria-label="Changer d’association">{spaces.map(s => <Link className="button secondary" aria-current={s.id === org.id ? 'page' : undefined} key={s.id} href={`/equipe?organisation=${s.id}`}>{s.name}</Link>)}</nav><div className="grid"><section className="card"><h2>Les membres</h2><ul className="item-list">{people.map(p => <li key={p.id}><strong>{p.name || p.email}</strong><span>{p.email}</span><Badge tone={p.revokedAt ? 'warning' : 'neutral'}>{p.revokedAt ? 'Accès retiré' : p.role === 'admin' ? 'Administrateur' : 'Membre'}</Badge><p>{p.professions.map(x => profiles[x as Profile]?.label || x).join(', ') || 'Métier à préciser'}</p>{org.role === 'admin' && !p.revokedAt && <details><summary>Gérer les accès</summary><TeamForm organizationId={org.id} operation="update-member" id={p.id} initial={p}/><TeamForm organizationId={org.id} operation="remove-member" id={p.id}/></details>}</li>)}</ul><p className="hint">Après un départ, les partages externes doivent être revus séparément.</p></section>{org.role === 'admin' && <section className="card"><h2>Inviter une personne</h2><Badge tone="info">Invitation personnelle · 48 heures</Badge><p>Une connexion de moins de cinq minutes est nécessaire.</p><Link href="/connexion">Me reconnecter pour confirmer mon identité →</Link><TeamForm organizationId={org.id} operation="invite"/><h2>Invitations</h2><ul className="item-list">{invites.map(i => <li key={i.id}><strong>{i.email}</strong><Badge tone={i.acceptedAt ? 'success' : i.revokedAt || i.expiresAt < new Date() ? 'neutral' : 'info'}>{i.acceptedAt ? 'Acceptée' : i.revokedAt ? 'Révoquée' : i.expiresAt < new Date() ? 'Expirée' : 'En attente d’acceptation'}</Badge>{!i.acceptedAt && !i.revokedAt && <TeamForm organizationId={org.id} operation="revoke-invitation" id={i.id}/>}</li>)}</ul></section>}</div></>;
}
