import Link from 'next/link';
import { requestLabels, type RequestStatus } from '../../../modules/work/models';
import { and, eq } from 'drizzle-orm';
import { programmeContext, MissingSpace } from '../../../modules/programme/context';
import { programmeService } from '../../../modules/programme/service';
import { AccessError, teamService } from '../../../modules/team/service';
import { projectGrants } from '../../../db/team-schema';
import { ProgrammeForm } from '../../../components/programme-form';
import { Badge } from '../../../components/ui/badge';
export const dynamic = 'force-dynamic';
export const metadata = { title: 'Fiche projet' };
export default async function Page({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ organisation?: string }> }) {
  const { actor, db, org } = await programmeContext((await searchParams).organisation); if (!org) return <MissingSpace/>;
  let result; try { result = await programmeService(db).get(actor, org.id, (await params).id); } catch (error) { if (error instanceof AccessError) return <MissingSpace/>; throw error; }
  const { project: p, brief, events, changes, canEdit } = result;
  const people = (await teamService(db).listMembers(actor, org.id)).filter(m => !m.revokedAt);
  const grants = org.role === 'admin' ? await db.select().from(projectGrants).where(eq(projectGrants.projectId, p.id)) : [];
  const fields = { organizationId: org.id, projectId: p.id, revision: p.revision };
  const person = (id: string | null) => people.find(m => m.id === id)?.name || (id ? 'Ancien membre / à réattribuer' : 'À désigner');
  return <><section className="page-title"><p className="eyebrow">{p.kind === 'event' ? 'ÉVÉNEMENT' : 'CAMPAGNE'} · {org.name}</p><h1>{p.title}</h1><Badge tone={p.status === 'preparation' ? 'info' : 'warning'}>{p.status === 'preparation' ? 'En préparation' : p.status === 'cancelled' ? 'Annulé' : 'Archivé'}</Badge><p>{p.eventType} · {p.ministry || 'Groupe non précisé'} · {p.timezone}</p></section><div className="quick-actions"><Link className="button secondary" href={`/projets/${p.id}/bilan?organisation=${org.id}`}>Suivi et bilan</Link><Link className="button secondary" href={`/contenus?organisation=${org.id}&projet=${p.id}`}>Contenus et livrables</Link><Link className="button secondary" href={`/projets?organisation=${org.id}`}>Tous les projets</Link><Link className="button secondary" href={`/calendrier?organisation=${org.id}&date=${p.startDate}`}>Voir au calendrier</Link></div><div className="grid"><section className="card"><h2>La demande de communication</h2><Badge tone={brief?.status === 'accepted' ? 'success' : 'warning'}>{requestLabels[brief?.status as RequestStatus]}</Badge><dl><dt>Objectif</dt><dd>{brief?.objective}</dd><dt>Public</dt><dd>{brief?.audience}</dd><dt>Message</dt><dd className="preserve-text">{brief?.message}</dd><dt>Ressources</dt><dd>{brief?.resources || 'À préciser'}</dd><dt>Date utile</dt><dd>{brief?.usefulDate || 'À préciser'}</dd><dt>Décideur</dt><dd>{person(brief?.decisionMakerId || null)}</dd></dl><Link className="button" href={`/projets/${p.id}/travail?organisation=${org.id}`}>Traiter la demande et préparer les tâches →</Link></section><section className="card"><h2>Informations pratiques</h2><dl><dt>Lieu</dt><dd>{p.location || 'À préciser'}</dd><dt>À savoir</dt><dd className="preserve-text">{p.practicalInfo || 'À préciser'}</dd><dt>Responsable</dt><dd>{person(p.ownerId)}</dd><dt>Validateur</dt><dd>{person(p.validatorId)}</dd><dt>Remplaçant</dt><dd>{person(p.deputyId)}</dd><dt>Niveau de communication</dt><dd>{{ essential: 'Essentiel', standard: 'Standard', extended: 'Étendu' }[p.communicationLevel] || p.communicationLevel}</dd></dl></section></div>
    <section className="card section-spaced"><h2>{p.kind === 'campaign' ? 'Période de la campagne' : 'Les occurrences'}</h2>{p.kind === 'campaign' ? <p>Du {p.startDate} au {p.endDate} inclus. Aucun faux événement n’est créé.</p> : <ul className="item-list">{events.map(event => <li key={event.id}><div className="section-head"><strong>{event.startDate}{event.endDate !== event.startDate ? ` → ${event.endDate}` : ''}</strong><Badge tone={event.status === 'cancelled' ? 'warning' : event.isException ? 'info' : 'neutral'}>{event.status === 'cancelled' ? 'Annulée' : event.isException ? 'Reportée · Exception' : 'Programmée'}</Badge></div><span>{p.allDay ? 'Journée entière' : `${event.startAt?.toLocaleTimeString('fr-FR', { timeZone: p.timezone, hour: '2-digit', minute: '2-digit' })} → ${event.endAt?.toLocaleTimeString('fr-FR', { timeZone: p.timezone, hour: '2-digit', minute: '2-digit' })}`} · {p.timezone}</span>{event.originalStartDate !== event.startDate && <small>Date initiale : {event.originalStartDate}</small>}{event.changeReason && <p>{event.changeReason}</p>}{canEdit && p.status === 'preparation' && event.status !== 'cancelled' && <details><summary>Modifier cette occurrence uniquement</summary><ProgrammeForm fields={{ ...fields, operation: 'occurrence', occurrenceId: event.id }}><label>Action<select name="change"><option value="reschedule">Reporter cette occurrence</option><option value="cancel">Annuler cette occurrence</option></select></label><label>Nouvelle date (pour un report)<input name="date" type="date" defaultValue={event.startDate}/></label><label>Nouvelle date de fin (facultative)<input name="endDate" type="date"/></label>{!p.allDay && <div className="field-grid"><label>Heure de début<input name="startTime" type="time" defaultValue={event.startAt?.toLocaleTimeString('en-GB', { timeZone: p.timezone, hour: '2-digit', minute: '2-digit' })}/></label><label>Heure de fin<input name="endTime" type="time" defaultValue={event.endAt?.toLocaleTimeString('en-GB', { timeZone: p.timezone, hour: '2-digit', minute: '2-digit' })}/></label></div>}<label>Motif<input name="reason" required minLength={5} maxLength={1000}/></label><p>Cette occurrence gardera son identité. Les autres dates ne changent pas.</p><button>Appliquer à cette occurrence</button></ProgrammeForm></details>}</li>)}</ul>}</section>
    {canEdit && <section className="card section-spaced"><h2>Gérer le projet</h2>{p.status === 'preparation' && <details><summary>Corriger le brief et les informations pratiques</summary><ProgrammeForm fields={{ ...fields, operation: 'brief' }}><label>Titre<input name="title" defaultValue={p.title} required minLength={2} maxLength={120}/></label><label>Objectif (facultatif)<textarea name="objective" defaultValue={brief?.objective} maxLength={2000}/></label><label>Public (facultatif)<input name="audience" defaultValue={brief?.audience} maxLength={500}/></label><label>Message (facultatif)<textarea name="message" defaultValue={brief?.message} maxLength={3000}/></label><label>Ressources<textarea name="resources" defaultValue={brief?.resources} maxLength={2000}/></label><label>Lieu<input name="location" defaultValue={p.location} maxLength={300}/></label><label>Informations pratiques<textarea name="practicalInfo" defaultValue={p.practicalInfo} maxLength={2000}/></label><button>Enregistrer les corrections</button></ProgrammeForm></details>}{p.status !== 'archived' && <details><summary>Reporter, annuler ou archiver {p.cadence !== 'none' ? 'la série' : 'le projet'}</summary><ProgrammeForm fields={{ ...fields, operation: 'project' }}><label>Action<select name="change">{p.status === 'preparation' && <><option value="reschedule">Reporter la période / les occurrences sans exception</option><option value="cancel">Annuler tout le projet, y compris les exceptions</option></>}<option value="archive">Archiver, en conservant toutes les données</option></select></label><label>Nouvelle première date (pour un report)<input name="date" type="date" defaultValue={p.startDate}/></label><label>Nouvelle première date de fin (facultative)<input name="endDate" type="date"/></label>{!p.allDay && <div className="field-grid"><label>Heure de début<input name="startTime" type="time" defaultValue={p.startTime || ''}/></label><label>Heure de fin<input name="endTime" type="time" defaultValue={p.endTime || ''}/></label></div>}<label>Motif<textarea name="reason" required minLength={5} maxLength={1000}/></label><p>Le report conserve les occurrences déjà reportées ou annulées individuellement. Une annulation globale touche toutes les occurrences. L’archivage ne termine aucune tâche.</p><label className="check-label"><input type="checkbox" required/>J’ai vérifié la portée de ce changement.</label><button>Appliquer au projet</button></ProgrammeForm></details>}</section>}
    {org.role === 'admin' && <section className="card section-spaced"><h2>Accès nominatifs à ce projet</h2><p>Une connexion de moins de cinq minutes est nécessaire. Les métiers n’accordent pas d’accès. Les permissions définies dans Équipe restent nécessaires.</p>{people.map(m => <details key={m.id}><summary>{m.name || m.email}</summary><ProgrammeForm fields={{ ...fields, operation: 'access', memberId: m.id }}>{[['project.read','Consulter'],['project.edit','Modifier'],['content.validate','Valider les contenus']].map(([permission,label]) => <label className="check-label" key={permission}><input type="checkbox" name="permissions" value={permission} defaultChecked={grants.some(g => g.memberId === m.id && g.permission === permission)}/>{label}</label>)}<button>Remplacer les accès de cette personne</button></ProgrammeForm></details>)}</section>}
    <section className="gentle-note"><h2>Historique et impacts à revoir</h2><p>Les changements de date nécessitent une revue des échéances des tâches. Les annulations suspendent le travail en conservant les données. Aucune action externe n’a été effectuée.</p><ul>{changes.map(c => <li key={c.id}>{c.createdAt.toLocaleDateString('fr-FR', { timeZone: p.timezone })} · {c.reason}</li>)}</ul></section></>;
}
