import Link from 'next/link';
type Item={id:string;title:string;plannedDate:string;channel:string;status:string};
export function EditorialCalendar({items,organizationId,month,filters}:{items:Item[];organizationId:string;month?:string;filters:Record<string,string|undefined>}){
 const current=new Date().toISOString().slice(0,7);
 const value=month&&/^\d{4}-(0[1-9]|1[0-2])$/.test(month)?month:current;
 const [y,m]=value.split('-').map(Number),first=new Date(Date.UTC(y,m-1,1)),days=new Date(Date.UTC(y,m,0)).getUTCDate(),offset=(first.getUTCDay()+6)%7;
 const href=(delta:number)=>{const date=new Date(Date.UTC(y,m-1+delta,1));const params=new URLSearchParams({organisation:organizationId,mois:date.toISOString().slice(0,7)});Object.entries(filters).forEach(([k,v])=>{if(v)params.set(k,v)});return `/contenus?${params}`;};
 return <section className="card section-spaced"><div className="section-head"><h2>{new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric',timeZone:'UTC'}).format(first)}</h2><div className="quick-actions"><Link aria-label="Mois précédent" href={href(-1)}>← Mois précédent</Link><Link aria-label="Mois suivant" href={href(1)}>Mois suivant →</Link></div></div><p>Dates de diffusion prévues. Ouvrez un contenu pour préparer, valider ou suivre sa publication.</p><div className="calendar-scroll"><div className="editorial-month">{['Lun','Mar','Mer','Jeu','Ven','Sam','Dim'].map(day=><strong className="editorial-day-name" key={day}>{day}</strong>)}{Array.from({length:offset},(_,i)=><div className="editorial-day blank" key={`blank-${i}`}/>)}{Array.from({length:days},(_,i)=>{const date=`${value}-${String(i+1).padStart(2,'0')}`;return <div className="editorial-day" key={date}><time dateTime={date}>{i+1}</time>{items.filter(item=>item.plannedDate===date).map(item=><Link className="editorial-entry" key={item.id} href={`/contenus/${item.id}?organisation=${organizationId}`}><strong>{item.title}</strong><span>{item.channel}</span></Link>)}</div>})}</div></div></section>;
}
