 'use client';
import {useEffect,useState} from 'react';
import {Uploader} from './uploader';
type Deposit={title:string;eventTitle:string;instructions:string;projectId:string;occurrenceId:string|null;startDate:string|null;acceptingUploads:boolean};
export function GuestUpload({token}:{token:string}) {
 const [code,setCode]=useState(''),[error,setError]=useState(''),[data,setData]=useState<Deposit|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setData(null);setError('');
  fetch('/api/collectes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,code:''}),signal:controller.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}).catch(e=>{if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Connexion interrompue.');}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return ()=>controller.abort();
 },[token]);
 return <section className="card">{loading?<p role="status">Ouverture du dépôt…</p>:!data?<><h1>Déposer des photos et vidéos</h1><p>Aucun compte nécessaire. Si l’association vous a donné un code de protection, saisissez-le ci-dessous. Sinon, demandez-lui un nouveau lien.</p><form onSubmit={async e=>{e.preventDefault();setError('');setLoading(true);try{const r=await fetch('/api/collectes',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,code})});const d=await r.json();if(!r.ok)throw new Error(d.error);setData(d);}catch(e){setError(e instanceof Error?e.message:'Connexion interrompue.');}finally{setLoading(false);}}}><label>Code de protection<input value={code} onChange={e=>setCode(e.target.value)} maxLength={100} autoComplete="off"/></label><button>Ouvrir le dépôt</button><p role="alert">{error}</p></form></>:<><h1>Déposer vos photos et vidéos</h1><p>Aucun compte à créer. Vos fichiers seront remis à l’association pour cet événement.</p><p>{data.instructions}</p>{data.acceptingUploads?<Uploader token={token} code={code} destination="rush" projects={[{id:data.projectId,title:data.eventTitle,events:data.occurrenceId?[{id:data.occurrenceId,startDate:data.startDate!,status:'scheduled'}]:[]}]}/>:<p role="status"><strong>{data.eventTitle}</strong> — Les dépôts ouvrent au début de l’événement{data.startDate?` du ${data.startDate}`:''}. Revenez pendant ou après celui-ci.</p>}</>}</section>;
}
