'use client';
import {useEffect,useRef,useState} from 'react';
import Link from 'next/link';
export type SearchPage={href:string;label:string;keywords:string};
const normalize=(value:string)=>value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('fr');
export function PageSearch({pages}:{pages:SearchPage[]}){
 const menu=useRef<HTMLDetailsElement>(null),input=useRef<HTMLInputElement>(null);const [query,setQuery]=useState('');
 useEffect(()=>{const outside=(e:Event)=>{if(e.target instanceof Node&&menu.current?.open&&!menu.current.contains(e.target))menu.current.open=false;};document.addEventListener('pointerdown',outside);document.addEventListener('focusin',outside);return()=>{document.removeEventListener('pointerdown',outside);document.removeEventListener('focusin',outside);};},[]);
 useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if(menu.current){menu.current.open=true;input.current?.focus();}}};document.addEventListener('keydown',shortcut);return()=>document.removeEventListener('keydown',shortcut);},[]);
 const results=pages.filter(p=>normalize(`${p.label} ${p.keywords}`).includes(normalize(query.trim())));
 return <details className="page-search" ref={menu} onToggle={()=>{if(menu.current?.open)input.current?.focus();}} onKeyDown={e=>{if(e.key==='Escape'&&menu.current){menu.current.open=false;menu.current.querySelector('summary')?.focus();}}}><summary aria-keyshortcuts="Control+k Meta+k"><span aria-hidden="true">⌕</span> <span>Rechercher</span></summary><div className="page-search-panel"><button type="button" className="secondary search-close" onClick={()=>{if(menu.current){menu.current.open=false;menu.current.querySelector('summary')?.focus();}}}>Fermer la recherche</button><label htmlFor="page-search-input">Rechercher une page ou une aide</label><input ref={input} id="page-search-input" type="search" autoComplete="off" placeholder="Photo, invitation, calendrier…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="hint">Recherche dans les rubriques, pas dans vos fichiers ou vos données.</p><nav aria-label="Résultats de recherche" onClick={e=>{if(e.target instanceof Element&&e.target.closest('a')&&menu.current){menu.current.open=false;setQuery('');}}}>{results.map(p=><Link key={p.href} href={p.href}>{p.label}</Link>)}</nav>{!results.length&&<p role="status">Aucune rubrique trouvée. Essayez « photo », « tâche » ou « aide ».</p>}</div></details>;
}
