'use client';
import {useId,useRef,useState,useTransition} from 'react';
import {createSHA256} from 'hash-wasm';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import styles from './uploader.module.css';
type Target={id:string;title:string;uploadOnly?:boolean;events:{id:string;startDate:string;status:string}[]};
const CHUNK=8*1024*1024;
function mime(file:File){const extensions:Record<string,string>={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',heic:'image/heic',heif:'image/heif',mp4:'video/mp4',mov:'video/quicktime',pdf:'application/pdf'};return file.type||extensions[file.name.split('.').pop()?.toLowerCase()||'']||'';}
export function Uploader({organizationId,projects,token,code='',canCreateProject=false,destination}:{organizationId?:string;projects:Target[];token?:string;code?:string;allowProposal?:boolean;canCreateProject?:boolean;destination?:'rush'|'deliverable'}){
 const router=useRouter(),selectId=useId(),stop=useRef(false);const [refreshing,startRefresh]=useTransition();
 const [project,setProject]=useState(projects[0]?.id||''),[event,setEvent]=useState(''),[category,setCategory]=useState(destination||'rush'),[files,setFiles]=useState<File[]>([]),[note,setNote]=useState(''),[guestName,setGuestName]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[phase,setPhase]=useState(''),[messages,setMessages]=useState<string[]>([]);
 const target=projects.find(p=>p.id===project),events=target?.events.filter(e=>e.status!=='cancelled')||[],eventId=event||events[0]?.id||null;
 async function upload(){setBusy(true);stop.current=false;setMessages([]);const headers:Record<string,string>=token?{'x-collection-token':token,'x-collection-code':code}:{'x-organization':organizationId||''};const api=async(path:string,method='GET',data?:unknown)=>{const r=await fetch(path,{method,headers:{...headers,...(data?{'content-type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});const body=await r.json();if(!r.ok)throw new Error(body.error||'Connexion temporairement indisponible.');return body;};
 try{for(const file of files){if(stop.current)break;const contentType=mime(file);if(!/^(image\/(jpeg|png|webp|heic|heif)|video\/(mp4|quicktime)|application\/pdf)$/.test(contentType)||(category==='rush'&&contentType==='application/pdf'))throw new Error(`${file.name} : format non accepté.`);
 setPhase(`Vérification de ${file.name}`);setProgress(0);const hasher=await createSHA256();hasher.init();for(let p=0;p<file.size;p+=CHUNK){if(stop.current)throw new Error('Envoi suspendu.');hasher.update(new Uint8Array(await file.slice(p,p+CHUNK).arrayBuffer()));setProgress(Math.min(100,Math.round((p+CHUNK)/file.size*100)));}const sha256=hasher.digest('hex');
 const identity=`ce-direct:${token||organizationId}:${project}:${eventId}:${category}:${sha256}`;let uploadKey=localStorage.getItem(identity);if(!uploadKey){uploadKey=crypto.randomUUID();localStorage.setItem(identity,uploadKey);}const init=await api('/api/drive-uploads','POST',{projectId:project,occurrenceId:eventId,uploadKey,name:file.name,mime:contentType,size:file.size,sha256,category,note,guestName});
 if(init.status==='uploading'){let state=await api(`/api/drive-uploads/${init.id}`);let offset=state.received;let attempts=0;setPhase(`Envoi direct dans Drive : ${file.name}`);setProgress(Math.round(offset/file.size*100));
 while(offset<file.size){if(stop.current)throw new Error('Envoi suspendu.');const end=Math.min(file.size,offset+CHUNK);try{const r=await fetch(init.uri,{method:'PUT',headers:{'content-type':contentType,'content-range':`bytes ${offset}-${end-1}/${file.size}`},body:file.slice(offset,end)});if(r.status!==308&&!r.ok)throw new Error('Envoi interrompu.');offset=end;attempts=0;setProgress(Math.round(offset/file.size*100));}catch{if(++attempts>3)throw new Error('Connexion interrompue. Sélectionnez le même fichier pour reprendre.');setPhase('Reprise de la connexion…');await new Promise(r=>setTimeout(r,1000*attempts));state=await api(`/api/drive-uploads/${init.id}`);offset=state.received;}}
 }
 const done=await api(`/api/drive-uploads/${init.id}`,'POST');setMessages(m=>[...m,`${file.name} : ${done.status==='classified'?'classé dans Drive':'reçu dans Drive, classement automatique en attente'}.`]);setProgress(100);
 }}catch(e){setMessages(m=>[...m,e instanceof Error?e.message:'Envoi interrompu. Votre fichier reste sur votre appareil.']);}finally{setBusy(false);setPhase('');}}
 return <form onSubmit={e=>{e.preventDefault();void upload();}}><fieldset disabled={busy}><div className={styles.eventHeader}><label htmlFor={selectId}>Événement</label>{!token&&canCreateProject&&<button type="button" className={styles.refresh} disabled={refreshing} onClick={()=>startRefresh(()=>router.refresh())}>↻ {refreshing?'Actualisation…':'Actualiser les événements'}</button>}</div><select id={selectId} value={project} onChange={e=>{setProject(e.target.value);setEvent('');}} required>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select>{events.length>0&&<label>Date de l’événement<select value={eventId||''} onChange={e=>setEvent(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.startDate}</option>)}</select></label>}{!token&&canCreateProject&&<p className={styles.createHint}><Link href={`/projets/nouveau?organisation=${organizationId}`} target="_blank">Créer un événement ↗</Link><span>Revenez ici puis actualisez la liste. Vos fichiers sélectionnés sont conservés.</span></p>}{!destination&&!token&&!target?.uploadOnly?<label>Catégorie<select value={category} onChange={e=>setCategory(e.target.value as 'rush'|'deliverable')}><option value="rush">Rushs</option><option value="deliverable">Livrables</option></select></label>:<p>Classement : <strong>{category==='rush'?'Rushs de l’événement':'Livrables'}</strong></p>}{token&&<label>Nom ou pseudonyme facultatif<input value={guestName} maxLength={100} onChange={e=>setGuestName(e.target.value)}/></label>}<label>Commentaire facultatif<textarea value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label><fieldset><legend>Choisir vos fichiers</legend><p>Photos JPEG, PNG, WebP, HEIC et vidéos MP4, MOV{category==='deliverable'?' ; PDF accepté':''}. Les fichiers de 200 Mo, 500 Mo ou 1 Go sont envoyés par fragments directement vers le Drive de l’association, selon l’espace disponible.</p><label>Photothèque / galerie<input type="file" multiple accept="image/*,video/*" onChange={e=>{if(e.target.files?.length)setFiles(Array.from(e.target.files));}}/></label><label>Parcourir les fichiers de l’appareil ou du cloud<input type="file" multiple onChange={e=>{if(e.target.files?.length)setFiles(Array.from(e.target.files));}}/></label>{files.length>0&&<p role="status">{files.length} fichier(s) : {files.map(f=>f.name).join(', ')}</p>}</fieldset><p>Année, événement, catégorie et dossiers Photos / Vidéos sont déterminés automatiquement. Gardez cette page ouverte pendant l’envoi. Après une coupure, sélectionnez les mêmes fichiers pour reprendre. Aucun examen manuel n’est demandé pour le classement.</p><button disabled={!files.length}>Envoyer / reprendre</button></fieldset>{busy&&<><p role="status">{phase}</p><progress aria-label={phase} value={progress} max={100}/><button type="button" className="secondary" onClick={()=>{stop.current=true;}}>Suspendre après ce fragment</button></>}<ul aria-live="polite">{messages.map((m,i)=><li key={i}>{m}</li>)}</ul></form>;
}
