'use client';
import {useId,useRef,useState,useTransition} from 'react';
import {createSHA256} from 'hash-wasm';
import {useRouter} from 'next/navigation';
import Link from 'next/link';
import styles from './uploader.module.css';
type Target={id:string;title:string;uploadOnly?:boolean;events:{id:string;startDate:string;status:string}[]};
const CHUNK=8*1024*1024;
function mime(file:File){const extensions:Record<string,string>={jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png',webp:'image/webp',heic:'image/heic',heif:'image/heif',mp4:'video/mp4',mov:'video/quicktime',pdf:'application/pdf'};return file.type||extensions[file.name.split('.').pop()?.toLowerCase()||'']||'';}
export function Uploader({organizationId,projects,token,code='',canCreateProject=false,destination}:{organizationId?:string;projects:Target[];token?:string;code?:string;allowProposal?:boolean;canCreateProject?:boolean;destination?:'rush'|'deliverable'}){
 const router=useRouter(),selectId=useId(),stop=useRef(false);const [refreshing,startRefresh]=useTransition();
 const [project,setProject]=useState(projects[0]?.id||''),[event,setEvent]=useState(''),[category,setCategory]=useState(destination||'rush'),[files,setFiles]=useState<File[]>([]),[note,setNote]=useState(''),[guestName,setGuestName]=useState(''),[busy,setBusy]=useState(false),[progress,setProgress]=useState(0),[phase,setPhase]=useState(''),[receipt,setReceipt]=useState(''),[error,setError]=useState(''),[sent,setSent]=useState(0),[inputKey,setInputKey]=useState(0);
 const target=projects.find(p=>p.id===project),events=target?.events.filter(e=>e.status!=='cancelled')||[],eventId=event||events[0]?.id||null;
 async function upload(){setBusy(true);stop.current=false;setReceipt('');setError('');setSent(0);const headers:Record<string,string>=token?{'x-collection-token':token,'x-collection-code':code}:{'x-organization':organizationId||''};const api=async(path:string,method='GET',data?:unknown)=>{const r=await fetch(path,{method,headers:{...headers,...(data?{'content-type':'application/json'}:{})},body:data?JSON.stringify(data):undefined});const body=await r.json();if(!r.ok)throw new Error(body.error||'Connexion temporairement indisponible.');return body;};
 try{for(const file of files){if(stop.current)break;const contentType=mime(file);if(!/^(image\/(jpeg|png|webp|heic|heif)|video\/(mp4|quicktime)|application\/pdf)$/.test(contentType)||(category==='rush'&&contentType==='application/pdf'))throw new Error(`${file.name} : format non accepté.`);
 setPhase(`Vérification de ${file.name}`);setProgress(0);const hasher=await createSHA256();hasher.init();for(let p=0;p<file.size;p+=CHUNK){if(stop.current)throw new Error('Envoi suspendu.');hasher.update(new Uint8Array(await file.slice(p,p+CHUNK).arrayBuffer()));setProgress(Math.min(100,Math.round((p+CHUNK)/file.size*100)));}const sha256=hasher.digest('hex');
 const identity=`ce-direct:${token||organizationId}:${project}:${eventId}:${category}:${sha256}`;let uploadKey=localStorage.getItem(identity);if(!uploadKey){uploadKey=crypto.randomUUID();localStorage.setItem(identity,uploadKey);}const init=await api('/api/drive-uploads','POST',{projectId:project,occurrenceId:eventId,uploadKey,name:file.name,mime:contentType,size:file.size,sha256,category,note,guestName});
 if(init.status==='uploading'){let state=await api(`/api/drive-uploads/${init.id}`);let offset=state.received;let attempts=0;setPhase(`Envoi direct dans Drive : ${file.name}`);setProgress(Math.round(offset/file.size*100));
 while(offset<file.size){if(stop.current)throw new Error('Envoi suspendu.');const end=Math.min(file.size,offset+CHUNK);try{const r=await fetch(init.uri,{method:'PUT',headers:{'content-type':contentType,'content-range':`bytes ${offset}-${end-1}/${file.size}`},body:file.slice(offset,end)});if(r.status!==308&&!r.ok)throw new Error('Envoi interrompu.');offset=end;attempts=0;setProgress(Math.round(offset/file.size*100));}catch{if(++attempts>3)throw new Error('Connexion interrompue. Sélectionnez le même fichier pour reprendre.');setPhase('Reprise de la connexion…');await new Promise(r=>setTimeout(r,1000*attempts));state=await api(`/api/drive-uploads/${init.id}`);offset=state.received;}}
 }
 const done=await api(`/api/drive-uploads/${init.id}`,'POST');if(!['ready','classified','classifying','failed'].includes(done.status))throw new Error(`${file.name} : réception non confirmée. Réessayez.`);setReceipt(file.name);setSent(n=>n+1);if(done.status==='failed')setError(`${file.name} est dans Drive, mais son classement doit être vérifié par un administrateur.`);setFiles(current=>current.filter(f=>f!==file));setInputKey(n=>n+1);setProgress(100);
 }}catch(e){setError(e instanceof Error?e.message:'Envoi interrompu. Votre fichier reste sur votre appareil.');}finally{setBusy(false);setPhase('');}}
 function selectFiles(list:FileList|null){if(!list?.length)return;setFiles(Array.from(list));setReceipt('');setError('');setSent(0);setInputKey(n=>n+1);}
 return <form className={styles.form} onSubmit={e=>{e.preventDefault();void upload();}}>
 <fieldset disabled={busy} className="form-body">
  <section className={styles.section}><h2>1. Votre événement</h2>
   {token?<p><strong>{target?.title}</strong></p>:<><label htmlFor={selectId}>Événement</label><select id={selectId} value={project} onChange={e=>{setProject(e.target.value);setEvent('');}} required>{projects.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></>}
   {events.length>1?<label>Date de l’événement<select value={eventId||''} onChange={e=>setEvent(e.target.value)}>{events.map(e=><option key={e.id} value={e.id}>{e.startDate}</option>)}</select></label>:events[0]&&<p className={styles.hint}>Date : {new Intl.DateTimeFormat('fr-FR',{dateStyle:'long',timeZone:'UTC'}).format(new Date(`${events[0].startDate}T12:00:00Z`))}</p>}
   {!token&&canCreateProject&&<div className={styles.eventActions}><Link href={`/projets/nouveau?organisation=${organizationId}`} target="_blank">Créer un événement ↗</Link><button type="button" className={styles.refresh} disabled={refreshing} onClick={()=>startRefresh(()=>router.refresh())}>{refreshing?'Actualisation…':'↻ Actualiser la liste'}</button></div>}
   {!destination&&!token&&!target?.uploadOnly&&<label>Destination<select value={category} onChange={e=>setCategory(e.target.value as 'rush'|'deliverable')}><option value="rush">Rushs</option><option value="deliverable">Livrables</option></select></label>}
  </section>
  <section className={styles.section}><h2>2. Vos fichiers</h2><p className={styles.hint}>Photos et vidéos{category==='deliverable'?', ou documents PDF':''}. Classement automatique dans les {category==='rush'?'Rushs':'Livrables'} de l’événement.</p>
   <div className={styles.pickers}><label>Photos et vidéos<input key={`gallery-${inputKey}`} type="file" multiple accept="image/*,video/*" onChange={e=>selectFiles(e.target.files)}/></label><label>Fichiers de l’appareil ou du cloud<input key={`files-${inputKey}`} type="file" multiple accept={category==='deliverable'?'image/*,video/*,.pdf':'image/*,video/*'} onChange={e=>selectFiles(e.target.files)}/></label></div>
   {files.length>0&&<div className={styles.selection}><div className={styles.eventActions}><strong>{files.length} fichier{files.length>1?'s':''} à envoyer</strong><button type="button" className={styles.refresh} onClick={()=>{setFiles([]);setInputKey(n=>n+1);}}>Vider la sélection</button></div><ul>{files.map((f,i)=><li key={`${f.name}-${i}`}><span>{f.name}</span><small>{(f.size/1024/1024).toLocaleString('fr-FR',{maximumFractionDigits:1})} Mo</small></li>)}</ul></div>}
   <details><summary>Ajouter une précision (facultatif)</summary>{token&&<label>Votre nom<input value={guestName} maxLength={100} onChange={e=>setGuestName(e.target.value)}/></label>}<label>Commentaire<textarea value={note} maxLength={1000} onChange={e=>setNote(e.target.value)}/></label></details>
   <p className={styles.hint}>Gardez cette page ouverte pendant l’envoi. En cas de coupure, reprenez avec les mêmes fichiers.</p><button className={styles.submit} disabled={!files.length}>Envoyer dans Drive</button>
  </section>
 </fieldset>
 {busy&&<div className={styles.feedback}><p role="status">{phase}</p><progress aria-label={phase} value={progress} max={100}/><button type="button" className={styles.refresh} onClick={()=>{stop.current=true;}}>Suspendre l’envoi</button></div>}
 {receipt&&<div className={styles.receipt} role="status"><strong>{sent} fichier{sent>1?'s':''} envoyé{sent>1?'s':''} dans Drive</strong><p>Dernier fichier : {receipt}</p></div>}
 {error&&<p className="notice" role="alert">{error}</p>}
 </form>;
}
