'use client';
import Link from 'next/link';
import { Badge } from './ui/badge';
import { useState } from 'react';
import { usePreview } from './workspace';
import { demoProjects, profiles } from '../modules/preview/data';
export function PageTitle({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) {
  return <section className="page-title"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{children}</p></section>;
}
export function Empty({ title, children, href, action }: { title: string; children: React.ReactNode; href?: string; action?: string }) {
  return <div className="empty"><span className="empty-symbol" aria-hidden="true">✧</span><h2>{title}</h2><p>{children}</p>{href && <Link className="button secondary" href={href}>{action}</Link>}</div>;
}
export function HomeView() {
  const { demo, profile } = usePreview(); const view = profiles[profile];
  return <><PageTitle eyebrow="VOTRE POINT DE RENCONTRE" title={view.title}>Retrouvez vos priorités et préparez la prochaine étape avec votre équipe.</PageTitle>
    <div className="quick-actions" aria-label="Accès rapides"><Link className="button" href="/taches">Mes tâches</Link><Link className="button secondary" href="/projets/nouveau">Préparer un événement</Link><Link className="button secondary" href="/medias/importer">Préparer un import</Link><Link className="button secondary" href="/contenus">Contenus et validations</Link></div>
    <div className="stat-grid">{[['Projets à préparer', demo ? '3' : '—'], [view.focus, demo ? '1' : '—'], ['Collectes récentes', '—']].map(([label, value]) => <div className="stat" key={label}><span>{label}</span><strong>{value}</strong><small>{demo ? 'Exemple de parcours' : 'Disponible dans une prochaine étape'}</small></div>)}</div>
    <div className="grid"><section className="card"><div className="section-head"><h2>Votre prochaine contribution</h2><Badge>{view.label}</Badge></div>{demo ? <><p className="eyebrow">EXEMPLE FICTIF · MISSION PROPOSÉE</p><h3>{view.task}</h3><p>Rencontre des bénévoles · La mission reste à accepter. Aucune action réelle n’est attendue.</p><Link className="text-link" href={view.link}>{view.action} →</Link></> : <Empty title="Vos priorités trouveront leur place ici">Activez les exemples fictifs pour explorer l’accueil de chaque métier. Les missions personnelles arriveront avec le module Travail.</Empty>}</section>
    <section className="card"><div className="section-head"><h2>À l’horizon</h2><Link href="/calendrier">Calendrier →</Link></div>{demo ? <ul className="item-list">{demoProjects.map(p => <li key={p.id}><time dateTime={p.date}>{p.displayDate}</time><Link href={'/projets#' + p.id}>{p.title}</Link><small>{p.kind} · Exemple fictif</small></li>)}</ul> : <Empty title="Un programme à construire">Retrouvez vos événements enregistrés dans Calendrier. Cet accueil reste une prévisualisation des vues métier.</Empty>}</section></div>
    <section className="gentle-note"><h2>Chaque chose en son temps.</h2><p>Vous pouvez enregistrer vos projets, préparer leurs dates et consulter le calendrier de votre association.</p><Link href="/reglages">Configurer mon espace →</Link></section></>;
}
export function ProjectsView() {
  const { demo } = usePreview(); const [filter, setFilter] = useState('Tous');
  return <><PageTitle eyebrow="PROJETS" title="Rassembler autour d’une intention.">Événements et campagnes partageront un même espace pour leur préparation, leur suivi et leurs livrables.</PageTitle><div className="section-head"><Link className="button" href="/projets/nouveau">Préparer un brief</Link><Link href="/taches">Tâches et missions →</Link></div>{demo ? <><div className="filters" role="group" aria-label="Filtrer les exemples">{['Tous','Événement','Campagne'].map(f => <button className="filter" key={f} aria-pressed={filter === f} onClick={() => setFilter(f)}>{f}</button>)}</div><div className="project-grid">{demoProjects.filter(p => filter === 'Tous' || p.kind === filter).map(p => <article className="card" key={p.id} id={p.id}><p className="eyebrow">{p.kind} · Exemple fictif</p><h2>{p.title}</h2><p>{p.description}</p><time dateTime={p.date}>{p.displayDate}</time><p><Badge tone={p.status === 'Brief à préciser' ? 'warning' : 'info'}>{p.status}</Badge></p><details><summary>Voir le parcours prévu</summary><p>Brief → préparation → production → validation → diffusion manuelle → bilan. Les tâches et livrables seront reliés à ce projet dans les étapes suivantes.</p></details></article>)}</div></> : <section className="card"><Empty title="Le premier projet commence par une idée" href="/projets/nouveau" action="Explorer le formulaire de brief">Le suivi des projets sera activé avec le module Programme. Vous pouvez déjà essayer le formulaire sans créer de projet.</Empty></section>}</>;
}
export function CalendarView() {
  const { demo } = usePreview();
  return <><PageTitle eyebrow="CALENDRIER" title="Donner du temps à chaque rencontre.">Une vue commune pour les événements et les campagnes de l’association.</PageTitle><section className="card"><div className="section-head"><h2>{demo ? 'Septembre 2026 · Agenda fictif' : 'Le calendrier de votre équipe'}</h2><Link href="/projets/nouveau">Préparer un événement →</Link></div>{demo ? <ul className="agenda">{demoProjects.map(p => <li key={p.id}><time dateTime={p.date}><strong>{p.date.slice(-2)}</strong>sept.</time><div><span className="eyebrow">{p.kind}</span><h3><Link href={'/projets#' + p.id}>{p.title}</Link></h3><p>Journée entière · Exemple fictif, sans rappel programmé</p></div></li>)}</ul> : <Empty title="Votre programme se prépare">L’agenda réel, les séries et les reports seront disponibles avec le module Programme.</Empty>}</section><p className="gentle-note">Google Calendar n’est pas connecté. Aucune date liturgique n’est ajoutée automatiquement.</p></>;
}
export function MediaView() {
  const { demo } = usePreview();
  return <><PageTitle eyebrow="MÉDIAS" title="Garder les bons moments à portée de main.">Les fichiers seront liés à leur projet, à leur version et aux autorisations de diffusion.</PageTitle><div className="import-panel"><div><h2>Préparer vos fichiers</h2><p>Découvrez les informations à réunir avant l’import. Le dépôt de fichiers n’est pas encore activé.</p></div><Link className="button" href="/medias/importer">Voir les étapes d’import</Link></div><section className="card">{demo ? <><p className="eyebrow">EXEMPLE FICTIF · AUCUN FICHIER STOCKÉ</p><h2>Photos de la rencontre</h2><p>Ce lot illustre un fichier en attente de contrôle.</p><Badge tone="warning">Droits à vérifier · Diffusion bloquée</Badge><p>Un fichier reçu ne sera disponible qu’après les contrôles et la copie vérifiée vers Drive.</p></> : <Empty title="Une médiathèque à construire">Le stockage privé, les dépôts et le classement Drive seront ajoutés dans les étapes dédiées aux fichiers.</Empty>}</section></>;
}
export function TeamView() {
  const { demo } = usePreview();
  return <><PageTitle eyebrow="ÉQUIPE" title="Des talents différents. Une même mission.">Les métiers orientent le travail ; les permissions déterminent les accès.</PageTitle><section className="card">{demo ? <><p className="eyebrow">PERSONNES FICTIVES · AUCUN COMPTE CRÉÉ</p><ul className="item-list"><li><strong>Camille · Exemple</strong><span>Coordination et photographie</span><small>Disponibilités à préciser</small></li><li><strong>Alex · Exemple</strong><span>Infographie</span><small>Accès à définir lors de l’invitation</small></li></ul></> : <Empty title="Votre équipe prendra place ici">Les invitations et comptes personnels seront réalisés à l’étape des accès. Aucun email n’est envoyé depuis cette version.</Empty>}</section><section className="gentle-note"><h2>Un métier n’accorde pas automatiquement des droits</h2><p>Chaque personne pourra cumuler des métiers. La validation de contenus et l’administration disposeront de permissions distinctes.</p><Link href="/reglages">Voir les services disponibles →</Link></section></>;
}
export function TasksView() {
  const { demo, profile } = usePreview();
  return <><PageTitle eyebrow="MES TÂCHES" title="Savoir où apporter votre aide.">Les missions proposées et les tâches acceptées garderont des états distincts.</PageTitle><section className="card">{demo ? <><p className="eyebrow">EXEMPLE FICTIF · PROPOSITION À EXAMINER</p><h2>{profiles[profile].task}</h2><p>Cette mission n’est pas acceptée. L’acceptation et les affectations seront disponibles avec le module Travail.</p><Link href="/projets#rencontre">Voir le projet d’exemple →</Link></> : <Empty title="Vos tâches personnelles arriveront ici">Le module Travail permettra de retrouver les missions qui vous sont proposées et celles que vous avez acceptées.</Empty>}</section></>;
}
export function ContentsView() {
  const { demo } = usePreview();
  return <><PageTitle eyebrow="CONTENUS ET VALIDATIONS" title="Un message relu, une diffusion préparée.">Brouillons, versions et décisions resteront liés au bon projet et au bon canal.</PageTitle><section className="card">{demo ? <><p className="eyebrow">EXEMPLE FICTIF · BROUILLON</p><h2>Invitation à la rencontre des bénévoles</h2><p>Exemple de texte : « Retrouvons-nous pour préparer ensemble les prochaines actions de solidarité. »</p><Badge tone="warning">Non approuvé · Pas prêt à publier</Badge><p>Le circuit de validation et le registre des droits seront ajoutés dans le module Production.</p></> : <Empty title="Vos premiers messages trouveront leur place ici">La création, les versions et les validations seront activées dans les étapes de production. Aucune publication n’est effectuée.</Empty>}</section></>;
}
