import Link from 'next/link';
import {programmeContext,MissingSpace} from '../../modules/programme/context';
export const dynamic='force-dynamic';
export const metadata={title:'Aide et tutoriel'};
export default async function Help({searchParams}:{searchParams:Promise<{organisation?:string}>}){
 const {org}=await programmeContext((await searchParams).organisation);if(!org)return <MissingSpace/>;
 const link=(path:string)=>`${path}?organisation=${org.id}`;
 const chapters=[['demarrage','Bien démarrer'],['evenements','Événements et projets'],['taches','Tâches et missions'],['fichiers','Photos, vidéos et fichiers'],['editorial','Calendrier éditorial'],['equipe','Équipe et invitations'],['google','Google Calendar et Drive'],['compte','Compte et navigation']];
 return <article className="help-guide"><section className="page-title"><p className="eyebrow">GUIDE COMÉTERNEL</p><h1>Aide et tutoriel</h1><p>Les étapes pour organiser votre association, préparer un événement et travailler ensemble.</p><p className="hint">Pour conserver ce guide : utilisez « Imprimer » dans votre navigateur, puis « Enregistrer au format PDF ».</p></section><nav className="card help-index" aria-label="Sommaire de l’aide"><h2>Sommaire</h2>{chapters.map(([id,title])=><a key={id} href={`#${id}`}>{title}</a>)}</nav>
 <section id="demarrage" className="card"><h2>1. Bien démarrer</h2><ol><li>Connectez-vous avec votre compte Google ou votre adresse email et votre mot de passe.</li><li>Créez l’espace de votre association, ou acceptez l’invitation de son administrateur avec l’adresse invitée.</li><li>Créez un événement : son nom, son type et sa date.</li><li>Organisez les tâches, ajoutez les participants et déposez les fichiers de l’événement.</li><li>Préparez les contenus, faites valider leur version, puis suivez leur publication.</li></ol><Link href={link('/')}>Revenir à l’accueil →</Link></section>
 <section id="evenements" className="card"><h2>2. Événements et projets</h2><p>La rubrique Projets regroupe vos événements et campagnes. L’événement sert à réunir les dates, le lieu, les tâches et les fichiers.</p><ol><li>Ouvrez Projets, puis Nouveau projet.</li><li>Renseignez le nom de l’événement, son type et sa date. Le lieu est facultatif.</li><li>Cochez « Journée entière » si les horaires ne sont pas nécessaires. Activez « Plusieurs jours » uniquement si besoin.</li><li>Complétez ensuite la préparation et les accès des participants.</li></ol><p>Si un événement n’apparaît pas, vérifiez l’association sélectionnée et demandez à votre administrateur de contrôler votre accès.</p><Link href={link('/projets')}>Ouvrir les projets →</Link></section>
 <section id="taches" className="card"><h2>3. Tâches et missions</h2><p>Mes tâches permet de suivre vos missions et vos disponibilités. Le tableau et la liste présentent le même travail sous deux formes.</p><ol><li>Choisissez Mes missions ou Toutes les tâches accessibles.</li><li>Ouvrez une tâche pour consulter son échéance, accepter la mission et mettre à jour son état.</li><li>Renseignez vos disponibilités pour faciliter la préparation des prochains événements.</li></ol><Link href={link('/taches')}>Ouvrir les tâches →</Link></section>
 <section id="fichiers" className="card"><h2>4. Importer des photos et vidéos</h2><ol><li>Ouvrez Photos et vidéos, puis Importer des photos et vidéos.</li><li>Sélectionnez un événement en préparation et sa date. Sans événement accessible, créez-en un si vous êtes autorisé ou contactez votre administrateur.</li><li>Choisissez le type de dépôt : Rush pour les originaux, Sélection pour les fichiers retenus, Création pour le travail en cours, Livrable pour un résultat à utiliser.</li><li>Ajoutez les fichiers, puis lancez Envoyer / reprendre. Formats acceptés : JPEG, PNG, WebP, MP4 et PDF ; 100 Mo maximum par fichier.</li><li>Attendez le message de réception. En cas d’interruption, sélectionnez le même fichier pour reprendre.</li></ol><p>Un fichier reçu doit encore être examiné. La réception ne signifie ni autorisation de diffusion ni copie dans Google Drive. Les fichiers en quarantaine demandent un contrôle.</p><p>Les collectes invitées permettent à un responsable autorisé de partager un lien de dépôt. L’invité utilise ce lien sans compte ComÉternel ou Google.</p><Link href={link('/medias/importer')}>Importer des photos et vidéos →</Link></section>
 <section id="editorial" className="card"><h2>5. Calendrier éditorial</h2><p>Le calendrier des événements indique quand l’événement a lieu. Le calendrier éditorial indique quand vous prévoyez de diffuser un contenu : ce sont deux dates différentes.</p><p>Préparez le contenu et ses versions, demandez la validation puis déclarez sa publication. Une version approuvée n’est pas automatiquement publiée sur un réseau social.</p><Link href={link('/contenus')}>Ouvrir le calendrier éditorial →</Link></section>
 <section id="equipe" className="card"><h2>6. Équipe et invitations</h2><p>L’administrateur invite une personne par email ou crée un code personnel à lui transmettre. Il choisit ses droits et vérifie les projets auxquels elle peut accéder.</p><p>Une demande d’accès attend la décision de l’administrateur. Une invitation envoyée doit ensuite être acceptée par son destinataire avec la bonne adresse email. Consultez le suivi des invitations et les courriers indésirables si nécessaire.</p><p>Le rôle Administrateur sert à gérer l’association. Le profil métier décrit le travail de la personne. L’accès aux projets et la validation des contenus dépendent des droits accordés.</p>{org.role==='admin'&&<Link href={link('/equipe')}>Gérer les membres et invitations →</Link>}</section>
 <section id="google" className="card"><h2>7. Google Calendar et Google Drive</h2><p>La connexion Google Calendar permet de publier les événements ComÉternel dans un calendrier dédié à l’association. Choisissez le compte Google à connecter et accordez les autorisations demandées. Les modifications dans Google Calendar ne sont pas synchronisées en retour.</p><p>Le transfert automatique des fichiers vers Google Drive avec n8n est en cours de préparation. Il ne faut pas considérer un dépôt dans ComÉternel comme une copie déjà effectuée dans Drive.</p>{org.role==='admin'&&<Link href={link('/reglages')}>Ouvrir les réglages de l’association →</Link>}</section>
 <section id="compte" className="card"><h2>8. Compte et navigation</h2><p>Sur téléphone, faites glisser le menu du haut de gauche à droite pour accéder aux rubriques. Rechercher retrouve les pages par mot-clé, par exemple photo, invitation ou calendrier.</p><p>Mon compte se ferme lorsque vous touchez ailleurs sur l’écran, choisissez un lien ou appuyez sur Échap. Pour changer d’association, utilisez le menu du compte si vous appartenez à plusieurs équipes.</p><p>La suppression du compte se demande dans Mon compte. Un délai de 30 jours permet d’annuler la demande ou de transférer l’administration pour conserver l’association.</p><Link href="/compte">Ouvrir mon compte →</Link></section>
 </article>;
}
