'use client';
import { useState } from 'react';
import { validPassword, passwordHint } from '../../modules/identity/password';
import { authClient } from '../../modules/identity/client';
export function LoginForm({googleEnabled,mailEnabled,linkError}: {googleEnabled:boolean;localMail:boolean;mailEnabled:boolean;linkError:boolean}) {
 const [mode,setMode]=useState<'login'|'signup'|'forgot'>('login');
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState('');
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [joinEmail,setJoinEmail]=useState(''),[code,setCode]=useState(''),[joinMessage,setJoinMessage]=useState(''),[joining,setJoining]=useState(false);
 return <><section className="page-title"><p className="eyebrow">COMÉTERNEL · VOTRE ASSOCIATION</p><h1>Connectez-vous à votre espace.</h1><p>Créez l’espace de votre association ou retrouvez les équipes auxquelles vous avez accès.</p></section>
 <div className="grid"><section className="card"><h2>{mode==='signup'?'Créer un compte':mode==='forgot'?'Mot de passe oublié':'Connexion avec mon adresse email'}</h2>
 {linkError&&<p role="alert">Le lien est invalide ou expiré. Recommencez votre demande.</p>}
 <form onSubmit={async e=>{e.preventDefault();if(mode!=='login'&&!mailEnabled){setMessage('Inscription par email indisponible : le service d’envoi des emails n’est pas encore configuré. Vous pouvez utiliser Connexion avec Google.');return;}setBusy(true);setMessage('');try{
 if(mode==='login'){const result=await authClient.signIn.email({email,password,callbackURL:'/compte'});if(result.error)setMessage('Connexion impossible. Vérifiez vos identifiants et la validation de votre adresse email.');else window.location.assign('/compte');}
 else if(mode==='signup'){const result=await authClient.signUp.email({email,password,name,callbackURL:'/compte'});setMessage(result.error?'Création impossible pour le moment. Réessayez.':'Consultez votre messagerie pour confirmer votre adresse avant de vous connecter.');}
 else {const result=await authClient.requestPasswordReset({email,redirectTo:'/nouveau-mot-de-passe'});setMessage(result.error?'Service indisponible pour le moment.':'Si un compte correspond à cette adresse, vous recevrez les instructions par email.');}
 }catch{setMessage('Service indisponible. Réessayez plus tard.');}finally{setBusy(false);setPassword('');}}}>
 {mode==='signup'&&<label>Votre nom<input required name="name" autoComplete="name" maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label>}
 <label>Adresse email<input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>
 {mode!=='forgot'&&<label>Mot de passe<input type="password" required minLength={mode==='signup'?6:1} aria-describedby={mode==='signup'?'password-help':undefined} maxLength={128} autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}
 {mode==='signup'&&<p id="password-help" className="password-help">{passwordHint} Votre adresse devra être confirmée par email.</p>}
 <p role="alert" className="form-feedback">{message}</p><button disabled={busy||(mode==='signup'&&!validPassword(password))}>{busy?'En cours…':mode==='login'?'Se connecter':mode==='signup'?'Créer mon compte':'Réinitialiser mon mot de passe'}</button></form>
 {!mailEnabled&&<p className="notice">La création de compte et la récupération du mot de passe seront disponibles après activation du service email.</p>}
 <div className="quick-actions">{(['login','signup','forgot'] as const).filter(x=>x!==mode).map(x=><button className="secondary" key={x} disabled={busy} onClick={()=>{setMode(x);setMessage('');setPassword('');}}>{x==='login'?'Revenir à la connexion':x==='signup'?'Créer un compte':'Mot de passe oublié ?'}</button>)}</div></section>
 <section className="card"><h2>Connexion avec Google</h2><p>Vous pourrez choisir le compte Google à utiliser, ou en ajouter un autre.</p><p>Utilisez le compte Google de votre association ou votre compte autorisé par son administrateur.</p><button disabled={busy||!googleEnabled} onClick={async()=>{setBusy(true);setMessage('');try{const r=await authClient.signIn.social({provider:'google',callbackURL:'/compte'});if(r.error)setMessage('Connexion Google indisponible.');}catch{setMessage('Connexion Google indisponible.');}finally{setBusy(false);}}}>Connexion avec Google</button></section></div>
 <section className="card join-association"><h2>Demander à rejoindre une association</h2><p>Saisissez le code fourni par l’association. Son administrateur recevra votre demande dans son espace et décidera de votre profil.</p><form onSubmit={async e=>{e.preventDefault();setJoining(true);setJoinMessage('');try{const r=await fetch('/api/demandes-acces',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:joinEmail,code})});const data=await r.json();setJoinMessage(data.message);}catch{setJoinMessage('Service indisponible. Votre saisie est conservée.');}finally{setJoining(false);}}}><label>Votre adresse email<input type="email" required maxLength={254} value={joinEmail} onChange={e=>setJoinEmail(e.target.value)}/></label><label>Code de l’association<input required minLength={16} maxLength={16} pattern="[a-fA-F0-9]{16}" autoCapitalize="characters" value={code} onChange={e=>setCode(e.target.value.trim().toUpperCase())}/></label><button disabled={joining}>{joining?'Envoi…':'Envoyer ma demande d’ajout'}</button><p role="status">{joinMessage}</p></form></section></>;
}
