'use client';
import { useState } from 'react';
import { validPassword, passwordHint } from '../../modules/identity/password';
import { authClient } from '../../modules/identity/client';
export function LoginForm({googleEnabled,mailEnabled,linkError,returnTo='/compte',joinCode='',initialEmail='',invitationName=''}: {googleEnabled:boolean;localMail:boolean;mailEnabled:boolean;linkError:boolean;returnTo?:string;joinCode?:string;initialEmail?:string;invitationName?:string}) {
 const [mode,setMode]=useState<'login'|'signup'|'forgot'>(invitationName?'signup':'login');
 const [email,setEmail]=useState(initialEmail),[password,setPassword]=useState(''),[name,setName]=useState('');
 const [confirmation,setConfirmation]=useState('');
 const [googleMessage,setGoogleMessage]=useState('');
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const [joinEmail,setJoinEmail]=useState(''),[code,setCode]=useState(joinCode),[joinMessage,setJoinMessage]=useState(''),[joining,setJoining]=useState(false);
 return <><section className="page-title"><p className="eyebrow">COMÉTERNEL · VOTRE ASSOCIATION</p><h1>{invitationName?`Rejoindre ${invitationName}`:'Connectez-vous à votre espace.'}</h1><p>{invitationName?'Votre adresse est déjà renseignée. Créez votre compte ou choisissez « J’ai déjà un compte ». Vous rejoindrez l’équipe après confirmation de votre adresse et acceptation de l’invitation.':'Choisissez Google ou votre adresse email. Pour rejoindre une équipe, utilisez votre invitation ou envoyez une demande ci-dessous.'}</p></section>
 <div className="auth-options"> <section className="card"><h2>1. Continuer avec Google</h2><p>Vous pourrez choisir le compte Google à utiliser, ou en ajouter un autre.</p><p>Si vous avez reçu une invitation, choisissez le compte correspondant à l’adresse invitée.</p><button disabled={busy||!googleEnabled} onClick={async()=>{setBusy(true);setGoogleMessage('');try{const r=await authClient.signIn.social({provider:'google',callbackURL:returnTo});if(r.error)setGoogleMessage('Connexion Google indisponible. Réessayez ou utilisez votre email ci-dessous.');}catch{setGoogleMessage('Connexion Google indisponible. Réessayez ou utilisez votre email ci-dessous.');}finally{setBusy(false);}}}>Connexion avec Google</button><p role="alert">{googleMessage}</p></section><section className="card"><h2>{mode==='signup'?'Créer un compte':mode==='forgot'?'Mot de passe oublié':'2. Continuer avec mon adresse email'}</h2>
 {linkError&&<p role="alert">Le lien est invalide ou expiré. Recommencez votre demande.</p>}
 <form onSubmit={async e=>{e.preventDefault();if(mode==='signup'&&password!==confirmation){setMessage('Les deux mots de passe doivent être identiques.');return;}if(mode!=='login'&&!mailEnabled){setMessage('Inscription par email indisponible : le service d’envoi des emails n’est pas encore configuré. Vous pouvez utiliser Connexion avec Google.');return;}setBusy(true);setMessage('');try{
 if(mode==='login'){const result=await authClient.signIn.email({email,password,callbackURL:returnTo});if(result.error)setMessage('Connexion impossible. Vérifiez vos identifiants et la validation de votre adresse email.');else window.location.assign(returnTo);}
 else if(mode==='signup'){const result=await authClient.signUp.email({email,password,name,callbackURL:returnTo});setMessage(result.error?'Création impossible pour le moment. Réessayez.':invitationName?'Confirmez votre adresse avec le lien reçu par email. Vous reviendrez directement sur votre invitation pour rejoindre l’équipe.':'Consultez votre messagerie pour confirmer votre adresse avant de vous connecter.');}
 else {const result=await authClient.requestPasswordReset({email,redirectTo:'/nouveau-mot-de-passe'});setMessage(result.error?'Service indisponible pour le moment.':'Si un compte correspond à cette adresse, vous recevrez les instructions par email.');}
 }catch{setMessage('Service indisponible. Réessayez plus tard.');}finally{setBusy(false);setPassword('');setConfirmation('');}}}>
 {mode==='signup'&&<label>Votre nom<input required name="name" autoComplete="name" maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label>}
 <label>Adresse email<input type="email" required autoComplete="email" readOnly={Boolean(initialEmail)} value={email} onChange={e=>setEmail(e.target.value)}/></label>
 {mode!=='forgot'&&<label>Mot de passe<input type="password" required minLength={mode==='signup'?6:1} aria-describedby={mode==='signup'?'password-help':undefined} maxLength={128} autoComplete={mode==='signup'?'new-password':'current-password'} value={password} onChange={e=>setPassword(e.target.value)}/></label>}
 {mode==='signup'&&<label>Confirmer le mot de passe<input type="password" required minLength={6} maxLength={128} autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} aria-describedby="password-match"/></label>}{mode==='signup'&&confirmation&&<p id="password-match" role="status">{password===confirmation?'Les deux mots de passe correspondent.':'Les deux mots de passe doivent être identiques.'}</p>}{mode==='signup'&&<p id="password-help" className="password-help">{passwordHint} Votre adresse devra être confirmée par email.</p>}
 <p role="alert" className="form-feedback">{message}</p><button disabled={busy||(mode==='signup'&&(!validPassword(password)||password!==confirmation))}>{busy?'En cours…':mode==='login'?'Se connecter':mode==='signup'?'Créer mon compte':'Réinitialiser mon mot de passe'}</button></form>
 {!mailEnabled&&<p className="notice">La création de compte et la récupération du mot de passe seront disponibles après activation du service email.</p>}
 <div className="quick-actions">{(['login','signup','forgot'] as const).filter(x=>x!==mode).map(x=><button className="secondary" key={x} disabled={busy} onClick={()=>{setMode(x);setMessage('');setPassword('');setConfirmation('');}}>{x==='login'?(invitationName?'J’ai déjà un compte':'Revenir à la connexion'):x==='signup'?'Créer un compte':'Mot de passe oublié ?'}</button>)}</div></section>

 {!invitationName&&<section className="card join-association" id="rejoindre"><h2>3. Rejoindre une association</h2><p>Vous avez déjà une invitation par email ? Ouvrez son lien, connectez-vous ou créez votre compte avec l’adresse invitée, puis acceptez pour rejoindre l’équipe.</p><details open={joinCode?true:undefined}><summary>Envoyer une demande d’ajout</summary><p>Pas encore invité ? Indiquez votre email et le code de l’association. Après accord de son administrateur, vous recevrez un lien d’invitation. Votre demande ne crée pas de compte et ne donne pas encore accès à l’équipe.</p><form onSubmit={async e=>{e.preventDefault();setJoining(true);setJoinMessage('');try{const r=await fetch('/api/demandes-acces',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email:joinEmail,code})});const data=await r.json();setJoinMessage(data.message);}catch{setJoinMessage('Service indisponible. Votre saisie est conservée.');}finally{setJoining(false);}}}><label>Votre adresse email<input type="email" required maxLength={254} value={joinEmail} onChange={e=>setJoinEmail(e.target.value)}/></label>{joinCode?<input type="hidden" value={code} readOnly/>:<label>Code de l’association<input required minLength={16} maxLength={16} pattern="[a-fA-F0-9]{16}" autoCapitalize="characters" value={code} onChange={e=>setCode(e.target.value.trim().toUpperCase())}/><span className="hint">Demandez ce code ou le lien de demande d’accès à votre association.</span></label>}<button disabled={joining}>{joining?'Envoi…':'Envoyer ma demande d’ajout'}</button><p role="status">{joinMessage}</p></form></details></section>}<p className="hint">Créer un compte ne vous rend pas administrateur d’une équipe existante. Vous devenez administrateur de l’espace d’association que vous créez vous-même.</p></div></>;
}
