import {EmailTest} from './email/form';
import {mailConfig} from '../../config/deployment';
import {eq} from 'drizzle-orm';
import {googleCalendars} from '../../db/team-schema';
import {CalendarForm} from './calendar/form';
import {canCreateTeam} from '../../config/owner';
import {Badge} from '../../components/ui/badge';
import {getDb} from '../../db/client';
import {requireSession} from '../../modules/identity/session';
import {teamService} from '../../modules/team/service';
import {driveConfig} from '../../modules/integrations/drive-transfers';
import {SetupForm} from '../setup-form';
import Link from 'next/link';
export const dynamic='force-dynamic';
export const metadata={title:'Réglages de l’équipe'};
export default async function Settings({searchParams}:{searchParams:Promise<{organisation?:string;nouvelle?:string;calendar?:string}>}){
 const actor=await requireSession();const spaces=await teamService(getDb()).listOrganizations(actor);const params=await searchParams;const requested=params.organisation;const admins=spaces.filter(s=>s.role==='admin');const selected=requested?admins.find(s=>s.id===requested):admins[0];
 if((params.nouvelle==='1'||(!requested&&!selected)) && canCreateTeam(actor.user))return <section className="card"><h1>Créer votre association</h1><p>Vous administrerez uniquement cette association. Invitez ensuite ses membres par email et attribuez leurs profils et leurs droits. Pour rejoindre une association existante, acceptez son invitation depuis votre compte.</p><SetupForm/></section>;
 if(!selected)return <section className="card"><h1>Les réglages sont réservés aux responsables.</h1><p>Votre compte permet de consulter les équipes qui vous ont invité. Pour modifier les réglages d’une équipe, contactez son administrateur.</p><Link className="button secondary" href="/compte">Mon compte</Link></section>;
 const [calendar]=await getDb().select({googleEmail:googleCalendars.googleEmail,status:googleCalendars.status,lastSyncedAt:googleCalendars.lastSyncedAt}).from(googleCalendars).where(eq(googleCalendars.organizationId,selected.id));
 let mailReady=false;try{mailConfig();mailReady=true;}catch{}
 const configured=driveConfig()?.organizationId===selected.id;
 return <><section className="page-title"><p className="eyebrow">ADMINISTRATION · {selected.name}</p><h1>Les réglages de votre équipe.</h1><p>Gérez les accès et les services de l’association dont vous êtes responsable.</p></section><div className="grid"><section className="card"><h2>Mes équipes à administrer</h2><ul className="spaces">{admins.map(space=><li key={space.id}><strong>{space.name}</strong><span>{space.timezone}</span><Link href={`/equipe?organisation=${space.id}`}>Membres et invitations →</Link><p><Link href={`/exploitation?organisation=${space.id}`}>Connexions et suivi →</Link></p></li>)}</ul>{canCreateTeam(actor.user)&&<details><summary>Créer une autre équipe</summary><SetupForm/></details>}</section><section className="card"><h2>Google Calendar</h2><p>Les événements, dates et lieux sont copiés de ComÉternel vers un calendrier dédié à votre association. Les modifications faites dans Google ne sont pas importées et peuvent être remplacées.</p>{params.calendar==='error'&&<p role="alert">Connexion Google Calendar impossible. Vérifiez la configuration Google et reconnectez-vous avant de réessayer.</p>}{calendar?<><p>Compte connecté : {calendar.googleEmail}</p><p role="status">{calendar.status==='synced'?'Synchronisé':calendar.status==='pending'?'Synchronisation en attente':calendar.status==='reconnect'?'Reconnexion Google nécessaire':'Échec de synchronisation : réessayez ou reconnectez Google.'}</p>{calendar.lastSyncedAt&&<p>Dernière réussite : {calendar.lastSyncedAt.toISOString()}</p>}<CalendarForm organizationId={selected.id} operation="sync"/><CalendarForm organizationId={selected.id} operation="disconnect"/></>:<p>Aucun calendrier Google connecté.</p>}<form action="/api/google-calendar/start" method="post"><input type="hidden" name="organizationId" value={selected.id}/><p>Cette connexion autorise ComÉternel à créer un calendrier dédié et à y publier les événements de l’association. Le compte Google choisi en sera propriétaire. Une connexion administrateur récente est nécessaire.</p><button>{calendar?'Reconnecter le même compte Google':'Connecter Google Calendar'}</button></form><h2>Services et accès</h2><ul className="item-list"><li><strong>Comptes et invitations</strong><Badge tone="success">Disponible</Badge></li><li><strong>Google Drive avec n8n</strong><Badge tone={configured?'info':'warning'}>{configured?'Paramètres renseignés · Test à confirmer':'À configurer'}</Badge></li><li><strong>Emails de connexion et invitations</strong><Badge tone={mailReady?'info':'warning'}>{mailReady?'Configuré · envoi à vérifier':'À configurer'}</Badge></li></ul><EmailTest/><p><Link href={`/exploitation?organisation=${selected.id}`}>Configurer et suivre les services →</Link></p><p><Link href="/compte">Mon compte et ma connexion →</Link></p><p>La connexion Google personnelle reste distincte du Drive utilisé pour les fichiers de l’équipe.</p></section></div></>;
}
