import {eq} from 'drizzle-orm';
import {googleCalendars} from '../../db/team-schema';
import {CalendarForm} from './calendar/form';
import {canCreateTeam} from '../../config/owner';
import {getDb} from '../../db/client';
import {requireSession} from '../../modules/identity/session';
import {teamService} from '../../modules/team/service';
import {SetupForm} from '../setup-form';
import Link from 'next/link';
import {DriveConnection} from '../../components/drive-connection';
export const dynamic='force-dynamic';
export const metadata={title:'Réglages de l’équipe'};
export default async function Settings({searchParams}:{searchParams:Promise<{organisation?:string;nouvelle?:string;calendar?:string;drive?:string}>}){
 const actor=await requireSession();const spaces=await teamService(getDb()).listOrganizations(actor);const params=await searchParams;const requested=params.organisation;const admins=spaces.filter(s=>s.role==='admin');const selected=requested?admins.find(s=>s.id===requested):admins[0];
 if((params.nouvelle==='1'||(!requested&&!selected)) && canCreateTeam(actor.user))return <section className="card"><h1>Créer votre association</h1><p>Vous administrerez uniquement cette association. Invitez ensuite ses membres par email et attribuez leurs profils et leurs droits. Pour rejoindre une association existante, acceptez son invitation depuis votre compte.</p><SetupForm/></section>;
 if(!selected)return <section className="card"><h1>Les réglages sont réservés aux responsables.</h1><p>Votre compte permet de consulter les équipes qui vous ont invité. Pour modifier les réglages d’une équipe, contactez son administrateur.</p><Link className="button secondary" href="/compte">Mon compte</Link></section>;
 const [calendar]=await getDb().select({googleEmail:googleCalendars.googleEmail,status:googleCalendars.status,lastSyncedAt:googleCalendars.lastSyncedAt}).from(googleCalendars).where(eq(googleCalendars.organizationId,selected.id));
 return <><section className="page-title"><p className="eyebrow">ADMINISTRATION · {selected.name}</p><h1>Réglages</h1><p>Les fichiers, le calendrier et les membres de votre association.</p></section><div className="settings-grid"><DriveConnection organizationId={selected.id} error={params.drive==='error'}/><section className="card"><h2>Associations et membres</h2><ul className="spaces">{admins.map(space=><li key={space.id}><strong>{space.name}</strong><span>{space.timezone}</span><Link href={`/equipe?organisation=${space.id}`}>Membres et invitations →</Link><p><Link href={`/exploitation?organisation=${space.id}`}>Historique des envois →</Link></p></li>)}</ul>{canCreateTeam(actor.user)&&<details><summary>Créer une autre association</summary><SetupForm/></details>}</section><section className="card"><h2>Google Calendar</h2><p>Publiez les événements de l’association dans un calendrier Google dédié. Modifiez les dates et les lieux depuis ComÉternel pour garder les deux à jour.</p>{params.calendar==='error'&&<p role="alert">Connexion Google Calendar impossible. Vérifiez la configuration Google et reconnectez-vous avant de réessayer.</p>}{calendar?<><p>Compte connecté : {calendar.googleEmail}</p><p role="status">{calendar.status==='synced'?'Synchronisé':calendar.status==='pending'?'Synchronisation en attente':calendar.status==='reconnect'?'Reconnexion Google nécessaire':'Échec de synchronisation : réessayez ou reconnectez Google.'}</p>{calendar.lastSyncedAt&&<p>Dernière réussite : {new Intl.DateTimeFormat('fr-FR',{dateStyle:'medium',timeStyle:'short',timeZone:selected.timezone}).format(calendar.lastSyncedAt)}</p>}<CalendarForm organizationId={selected.id} operation="sync"/><CalendarForm organizationId={selected.id} operation="disconnect"/></>:<p>Aucun calendrier Google connecté.</p>}<form action="/api/google-calendar/start" method="post"><input type="hidden" name="organizationId" value={selected.id}/><p>Choisissez le compte Google qui hébergera le calendrier de l’association.</p><button>{calendar?'Reconnecter le même compte Google':'Connecter Google Calendar'}</button></form></section></div></>;
}
