import {contentAssets} from './content-assets';
import {and,eq,inArray,asc,desc,ne} from 'drizzle-orm';
import {z} from 'zod';
import {contents,contentVersions,decisions,publications,media,productionHistory} from '../../db/production-schema';
import {type Actor,AccessError} from '../team/service';
import {programmeService} from '../programme/service';
import {todayIn,isoDate} from '../programme/dates';
import {type DB,type Conn,access,active,lock,ProductionError} from './access';
import {hash} from './storage';
const url=z.union([z.literal(''),z.url().refine(s=>['https:','http:'].includes(new URL(s).protocol))]);
export const rightsSchema=z.object({author:z.string().trim().min(3).max(500),people:z.enum(['authorized','not_applicable','unknown']),music:z.enum(['authorized','not_applicable','unknown']),minors:z.enum(['authorized','not_applicable','unknown']),channels:z.array(z.string().trim().min(1).max(100)).min(1).max(20),evidence:z.string().trim().min(5).max(2000),reviewDate:isoDate,reviewer:z.string().trim().min(2).max(200),withdrawn:z.boolean()});
const inputSchema=z.object({title:z.string().trim().min(3).max(180),channel:z.string().trim().min(2).max(100),format:z.string().trim().min(2).max(100),plannedDate:isoDate,occurrenceId:z.uuid().nullable(),caption:z.string().trim().min(5).max(15000),brief:z.string().trim().min(5).max(5000),practicalUrl:url,creationUrl:url,reference:z.string().max(2000),mediaIds:z.array(z.uuid()).max(30),rights:rightsSchema.nullable()});
export function rightsValid(rights:typeof media.$inferSelect.rights,channel:string,today:string){return !!rights&&!rights.withdrawn&&rights.channels.includes(channel)&&rights.reviewDate>=today&&![rights.people,rights.music,rights.minors].includes('unknown');}
export function contentService(db:DB){
 async function current(c:Conn,id:string){z.uuid().parse(id);const [item]=await c.select().from(contents).where(eq(contents.id,id));if(!item)throw new AccessError();const [version]=await c.select().from(contentVersions).where(and(eq(contentVersions.contentId,id),eq(contentVersions.number,item.currentVersion)));if(!version)throw new ProductionError('Version indisponible.');return {item,version};}
 async function fingerprint(c:Conn,item:typeof contents.$inferSelect,version:typeof contentVersions.$inferSelect,timezone:string){const assets=await contentAssets(c,version.mediaIds.length?await c.select().from(media).where(inArray(media.id,version.mediaIds)):[]);if(assets.length!==new Set(version.mediaIds).size||assets.some(m=>m.organizationId!==item.organizationId||m.projectId!==item.projectId||!m.contentReady))throw new ProductionError('Sélectionnez des livrables reçus et vérifiés appartenant à ce projet.');const today=todayIn(timezone);if(!rightsValid(version.rights,version.channel,today)||assets.some(m=>!rightsValid(m.rights,version.channel,today)))throw new ProductionError('Droits incomplets, retirés ou à réexaminer pour ce canal.');return hash(JSON.stringify({version:version.id,rights:version.rights,assets:assets.sort((a,b)=>a.id.localeCompare(b.id)).map(m=>({id:m.id,revision:m.revision,sha256:m.sha256,rights:m.rights}))}));}
 async function approved(c:Conn,item:typeof contents.$inferSelect,version:typeof contentVersions.$inferSelect,timezone:string){if(item.status!=='approved')throw new ProductionError('Cette version doit être approuvée avant diffusion.');const fp=await fingerprint(c,item,version,timezone);const [last]=await c.select().from(decisions).where(and(eq(decisions.versionId,version.id),ne(decisions.decision,'comment'))).orderBy(desc(decisions.createdAt));if(!last||last.decision!=='approved'||last.fingerprint!==fp)throw new ProductionError('Cette version et ses droits doivent être approuvés à nouveau.');return fp;}
 return {
 async list(a:Actor,org:string){const ps=await programmeService(db).list(a,org);return {projects:ps,items:ps.length?await db.select().from(contents).where(inArray(contents.projectId,ps.map(p=>p.id))).orderBy(asc(contents.plannedDate)):[]};},
 async get(a:Actor,org:string,id:string){const {item,version}=await current(db,id);const {p}=await access(db,a,org,item.projectId);let canEdit=false,canValidate=false;try{await access(db,a,org,item.projectId,'edit');canEdit=true;}catch{}try{await access(db,a,org,item.projectId,'validate');canValidate=true;}catch{}const assets=await contentAssets(db,await db.select().from(media).where(and(eq(media.projectId,item.projectId),eq(media.organizationId,org))));const history=await db.select().from(decisions).where(eq(decisions.contentId,id)).orderBy(asc(decisions.createdAt));const versions=await db.select().from(contentVersions).where(eq(contentVersions.contentId,id)).orderBy(desc(contentVersions.number));const pubs=await db.select().from(publications).where(eq(publications.contentId,id));let ready=false,blocker='';try{await active(db,p,item.occurrenceId);await approved(db,item,version,p.timezone);ready=true;}catch(e){blocker=e instanceof Error?e.message:'À vérifier';}return {item,version,project:p,assets,history,versions,publications:pubs,canEdit,canValidate,ready,blocker};},
 async save(a:Actor,org:string,projectId:string,creationKey:string,input:unknown,id?:string,revision?:number){const v=inputSchema.parse(input);z.uuid().parse(creationKey);return db.transaction(async tx=>{await lock(tx,org);const {p}=await access(tx,a,org,projectId,'edit');await active(tx,p,v.occurrenceId);if(new Set(v.mediaIds).size!==v.mediaIds.length)throw new ProductionError('Un fichier est sélectionné plusieurs fois.');for(const mid of v.mediaIds){const [m]=await tx.select().from(media).where(and(eq(media.id,mid),eq(media.organizationId,org),eq(media.projectId,projectId)));if(!m||!(await contentAssets(tx,[m]))[0].contentReady)throw new ProductionError('Sélectionnez des livrables reçus et vérifiés de ce projet.');}
 let item:typeof contents.$inferSelect;let number=1;if(id){const old=await current(tx,id);if(old.item.projectId!==projectId||old.item.revision!==revision)throw new ProductionError('Le contenu a changé. Actualisez avant de modifier.');number=old.item.currentVersion+1;[item]=await tx.update(contents).set({title:v.title,channel:v.channel,format:v.format,plannedDate:v.plannedDate,occurrenceId:v.occurrenceId,status:'draft',currentVersion:number,revision:old.item.revision+1}).where(eq(contents.id,id)).returning();await tx.update(publications).set({status:'obsolete'}).where(and(eq(publications.contentId,id),eq(publications.status,'prepared')));}else{const [existing]=await tx.select().from(contents).where(and(eq(contents.organizationId,org),eq(contents.creationKey,creationKey)));if(existing){if(existing.createdBy!==a.user.id)throw new AccessError();throw new ProductionError('Ce contenu a déjà été créé. Ouvrez-le pour le modifier.');}[item]=await tx.insert(contents).values({organizationId:org,projectId,creationKey,title:v.title,channel:v.channel,format:v.format,plannedDate:v.plannedDate,occurrenceId:v.occurrenceId,createdBy:a.user.id}).returning();}await tx.insert(contentVersions).values({contentId:item.id,number,caption:v.caption,brief:v.brief,practicalUrl:v.practicalUrl,creationUrl:v.creationUrl,reference:v.reference,mediaIds:v.mediaIds,rights:v.rights,channel:v.channel,createdBy:a.user.id});return item;});},
 async submit(a:Actor,org:string,id:string,revision:number){return db.transaction(async tx=>{await lock(tx,org);const {item}=await current(tx,id);const {p}=await access(tx,a,org,item.projectId,'edit');await active(tx,p,item.occurrenceId);if(item.revision!==revision||!['draft','changes'].includes(item.status))throw new ProductionError('Version à actualiser ou déjà soumise.');await tx.update(contents).set({status:'submitted',revision:item.revision+1}).where(eq(contents.id,id));});},
 async decide(a:Actor,org:string,id:string,revision:number,decision:unknown,reason:string){const choice=z.enum(['approved','changes','comment']).parse(decision);reason=z.string().trim().min(5).max(3000).parse(reason);return db.transaction(async tx=>{await lock(tx,org);const {item,version}=await current(tx,id);const {p}=await access(tx,a,org,item.projectId,choice==='comment'?'read':'validate');await active(tx,p,item.occurrenceId);if(item.revision!==revision)throw new ProductionError('Le contenu a changé.');if(choice!=='comment'&&!['submitted','approved'].includes(item.status))throw new ProductionError('Soumettez cette version avant de décider.');const fp=choice==='approved'?await fingerprint(tx,item,version,p.timezone):'';await tx.insert(decisions).values({contentId:id,versionId:version.id,actorId:a.user.id,decision:choice,reason,fingerprint:fp});if(choice!=='comment')await tx.update(contents).set({status:choice,revision:item.revision+1}).where(eq(contents.id,id));});},
 async rights(a:Actor,org:string,mediaId:string,revision:number,input:unknown){const value=rightsSchema.parse(input);return db.transaction(async tx=>{await lock(tx,org);const [m]=await tx.select().from(media).where(and(eq(media.id,mediaId),eq(media.organizationId,org)));if(!m||m.revision!==revision)throw new ProductionError('Fichier à actualiser.');await access(tx,a,org,m.projectId,'validate');await tx.update(media).set({rights:value,revision:m.revision+1}).where(eq(media.id,mediaId));await tx.insert(productionHistory).values({organizationId:org,projectId:m.projectId,actorId:a.user.id,action:value.withdrawn?'rights_withdrawn':'rights_updated',reason:value.evidence});});},
 async prepare(a:Actor,org:string,id:string,revision:number,responseOwner:string){responseOwner=z.string().trim().min(2).max(150).parse(responseOwner);return db.transaction(async tx=>{await lock(tx,org);const {item,version}=await current(tx,id);const {p}=await access(tx,a,org,item.projectId,'edit');await active(tx,p,item.occurrenceId);if(item.revision!==revision)throw new ProductionError('Contenu modifié.');const fp=await approved(tx,item,version,p.timezone);const [old]=await tx.select().from(publications).where(eq(publications.versionId,version.id));if(old){if(old.fingerprint!==fp||old.status==='withdrawn')throw new ProductionError('Préparation périmée : créez une nouvelle version et faites-la approuver.');return old;}const [pub]=await tx.insert(publications).values({contentId:id,versionId:version.id,fingerprint:fp,responseOwner,actorId:a.user.id}).returning();return pub;});},
 async publish(a:Actor,org:string,id:string,proof:string,date:string){proof=z.string().trim().min(8).max(2000).parse(proof);const publishedAt=new Date(z.iso.datetime({offset:true}).parse(date));if(publishedAt.getTime()>Date.now()+60000)throw new ProductionError('Une diffusion effectuée ne peut pas être datée dans le futur.');return db.transaction(async tx=>{await lock(tx,org);const {item,version}=await current(tx,id);const {p}=await access(tx,a,org,item.projectId,'edit');await active(tx,p,item.occurrenceId);const fp=await approved(tx,item,version,p.timezone);const [pub]=await tx.select().from(publications).where(eq(publications.versionId,version.id));if(!pub||pub.status!=='prepared'||pub.fingerprint!==fp)throw new ProductionError('Préparez la version approuvée avant de déclarer sa diffusion.');await tx.update(publications).set({status:'published',proof,publishedAt}).where(eq(publications.id,pub.id));});},
 async withdraw(a:Actor,org:string,id:string,motif:string){motif=z.string().trim().min(5).max(2000).parse(motif);return db.transaction(async tx=>{await lock(tx,org);const {item}=await current(tx,id);await access(tx,a,org,item.projectId,'edit');await tx.update(contents).set({status:'withdrawn',revision:item.revision+1}).where(eq(contents.id,id));await tx.update(publications).set({status:'withdrawn'}).where(eq(publications.contentId,id));await tx.insert(productionHistory).values({organizationId:org,projectId:item.projectId,actorId:a.user.id,action:'withdrawal_requested',reason:motif+' — Vérifier manuellement le retrait sur chaque canal déjà utilisé.'});});},
 async export(a:Actor,org:string,id:string){const d=await this.get(a,org,id);if(!d.canEdit||!d.ready||d.item.status==='withdrawn')throw new ProductionError('Version non prête à exporter.');return {title:d.item.title,version:d.version.number,channel:d.version.channel,caption:d.version.caption,practicalUrl:d.version.practicalUrl,reference:d.version.reference,media:d.version.mediaIds.map(id=>({id,url:`/api/medias/${id}?organisation=${org}`})),warning:'Paquet manuel : revérifier la version dans ComÉternel avant diffusion. Aucune publication effectuée par cet export.'};}
 };
}
