import {randomBytes} from 'node:crypto';
import {and,eq,asc,inArray} from 'drizzle-orm';
import {z} from 'zod';
import {media,mediaParts,collections,productionHistory} from '../../db/production-schema';
import {projects} from '../../db/programme-schema';
import {programmeService} from '../programme/service';
import {type Actor,AccessError,requireFresh} from '../team/service';
import {type DB,type Conn,access,active,lock,ProductionError} from './access';
import {hash,store,read,MAX_FILE,CHUNK,detected} from './storage';
const reason=z.string().trim().min(5).max(2000);
export type UploadActor={actor:Actor;org:string}|{token:string;code:string};
export function mediaService(db:DB){
 async function collection(c:Conn,token:string,code:string){if(token.length<32||token.length>100)throw new AccessError();const [v]=await c.select().from(collections).where(eq(collections.tokenHash,hash(token)));if(!v||v.revokedAt||v.expiresAt.getTime()<Date.now()||(v.codeHash&&v.codeHash!==hash(code)))throw new AccessError('Lien expiré, révoqué ou code incorrect.');const [p]=await c.select().from(projects).where(eq(projects.id,v.projectId));await active(c,p,v.occurrenceId);return v;}
 async function uploadAccess(c:Conn,who:UploadActor,id:string){z.uuid().parse(id);const [m]=await c.select().from(media).where(eq(media.id,id));if(!m)throw new AccessError();if('actor'in who){const {p}=await access(c,who.actor,who.org,m.projectId);if(m.organizationId!==who.org||m.createdBy!==who.actor.user.id)throw new AccessError();await active(c,p,m.occurrenceId);}else{const v=await collection(c,who.token,who.code);if(m.collectionId!==v.id)throw new AccessError();}return m;}
 return {
 async list(a:Actor,org:string){const ps=await programmeService(db).list(a,org);return {projects:ps,media:ps.length?await db.select().from(media).where(inArray(media.projectId,ps.map(p=>p.id))).orderBy(asc(media.createdAt)):[]};},
 async guest(token:string,code:string){const c=await collection(db,token,code);return {id:c.id,title:c.title,instructions:c.instructions,allowProposal:c.allowProposal,maxBytes:c.maxBytes,maxFiles:c.maxFiles,projectId:c.projectId,occurrenceId:c.occurrenceId};},
 async createCollection(a:Actor,org:string,projectId:string,input:unknown){const v=z.object({title:z.string().trim().min(3).max(150),instructions:z.string().trim().min(5).max(2000),expiresAt:z.coerce.date(),maxFiles:z.coerce.number().int().min(1).max(100),maxBytes:z.coerce.number().int().min(1).max(1024*1024*1024),code:z.string().max(100).default(''),allowProposal:z.boolean(),occurrenceId:z.uuid().nullable()}).parse(input);if(v.expiresAt.getTime()<=Date.now()||v.expiresAt.getTime()>Date.now()+90*86400000)throw new ProductionError('Choisissez une expiration dans les 90 prochains jours.');return db.transaction(async tx=>{await lock(tx,org);const {p}=await access(tx,a,org,projectId,'edit');await active(tx,p,v.occurrenceId);const token=randomBytes(32).toString('base64url');const [c]=await tx.insert(collections).values({...v,organizationId:org,projectId,createdBy:a.user.id,tokenHash:hash(token),codeHash:v.code?hash(v.code):null}).returning();return {id:c.id,token};});},
 async listCollections(a:Actor,org:string,projectId:string){await access(db,a,org,projectId,'edit');return db.select({id:collections.id,title:collections.title,expiresAt:collections.expiresAt,revokedAt:collections.revokedAt}).from(collections).where(eq(collections.projectId,projectId));},
 async revoke(a:Actor,org:string,id:string){z.uuid().parse(id);return db.transaction(async tx=>{await lock(tx,org);const [c]=await tx.select().from(collections).where(and(eq(collections.id,id),eq(collections.organizationId,org)));if(!c)throw new AccessError();await access(tx,a,org,c.projectId,'edit');await tx.update(collections).set({revokedAt:new Date()}).where(eq(collections.id,id));});},
 async begin(who:UploadActor,input:unknown){const v=z.object({projectId:z.uuid(),occurrenceId:z.uuid().nullable(),uploadKey:z.uuid(),name:z.string().trim().min(1).max(180),mime:z.enum(['image/jpeg','image/png','image/webp','video/mp4','application/pdf']),size:z.number().int().min(1).max(MAX_FILE),sha256:z.string().regex(/^[a-f0-9]{64}$/),category:z.enum(['rush','selection','creation','deliverable']),guestName:z.string().max(100).default(''),note:z.string().max(1000).default(''),proposalTitle:z.string().max(150).default(''),proposalDate:z.string().default('')}).parse(input);const guest='token'in who?await collection(db,who.token,who.code):null;const org='actor'in who?who.org:guest!.organizationId;
 return db.transaction(async tx=>{await lock(tx,org);let c=guest;if('actor'in who){const {p}=await access(tx,who.actor,org,v.projectId);await active(tx,p,v.occurrenceId);}else{c=await collection(tx,who.token,who.code);if(c.projectId!==v.projectId||c.occurrenceId!==v.occurrenceId)throw new AccessError();if(v.proposalTitle&&!c.allowProposal)throw new AccessError();}const [previous]=await tx.select().from(media).where(and(eq(media.organizationId,org),eq(media.uploadKey,v.uploadKey)));if(previous){await uploadAccess(tx,who,previous.id);if(previous.sha256!==v.sha256||previous.size!==v.size||previous.projectId!==v.projectId||previous.occurrenceId!==v.occurrenceId)throw new ProductionError('Cet envoi correspond à un autre fichier.');return {id:previous.id,received:previous.received,state:previous.state};}
 const current=await tx.select().from(media).where(eq(media.organizationId,org));if(current.reduce((sum,m)=>sum+m.size,0)+v.size>2*1024*1024*1024)throw new ProductionError('Quota local de 2 Go atteint. Aucun fichier existant supprimé.');if(c){const mine=current.filter(m=>m.collectionId===c!.id);if(mine.length>=c.maxFiles||mine.reduce((n,m)=>n+m.size,0)+v.size>c.maxBytes)throw new ProductionError('Quota de collecte atteint.');}const [m]=await tx.insert(media).values({...v,organizationId:org,createdBy:'actor'in who?who.actor.user.id:null,collectionId:c?.id,proposalTitle:v.proposalTitle||null,proposalDate:v.proposalTitle?z.iso.date().parse(v.proposalDate):null,proposalState:v.proposalTitle?'pending':null}).returning();return {id:m.id,received:0,state:m.state};});},
 async chunk(who:UploadActor,id:string,offset:number,bytes:Buffer){if(!Number.isSafeInteger(offset)||offset<0||!bytes.length||bytes.length>CHUNK)throw new ProductionError('Fragment invalide.');const first=await uploadAccess(db,who,id);return db.transaction(async tx=>{await lock(tx,first.organizationId);const m=await uploadAccess(tx,who,id);const fingerprint=hash(bytes);const [previous]=await tx.select().from(mediaParts).where(and(eq(mediaParts.mediaId,id),eq(mediaParts.offset,offset)));if(previous){if(previous.hash!==fingerprint)throw new ProductionError('Le fragment reçu est différent.');return m.received;}if(m.state!=='uploading'||offset!==m.received||offset+bytes.length>m.size)throw new ProductionError('Reprenez l’envoi depuis la position confirmée.');const key=`${m.organizationId}/${m.id}/part_${offset}`;await store(key,bytes);await tx.insert(mediaParts).values({mediaId:id,offset,size:bytes.length,hash:fingerprint,key});await tx.update(media).set({received:offset+bytes.length}).where(eq(media.id,id));return offset+bytes.length;});},
 async complete(who:UploadActor,id:string){const first=await uploadAccess(db,who,id);return db.transaction(async tx=>{await lock(tx,first.organizationId);const m=await uploadAccess(tx,who,id);if(m.state!=='uploading')return {id:m.id,state:m.state};if(m.received!==m.size)throw new ProductionError('Envoi incomplet : vos fragments restent conservés.');const parts=await tx.select().from(mediaParts).where(eq(mediaParts.mediaId,id)).orderBy(asc(mediaParts.offset));const chunks=[];for(const p of parts){const b=await read(p.key);if(hash(b)!==p.hash)throw new ProductionError('Fragment endommagé. Reprenez avec un nouvel envoi.');chunks.push(b);}const bytes=Buffer.concat(chunks);if(bytes.length!==m.size||hash(bytes)!==m.sha256)throw new ProductionError('Intégrité du fichier non confirmée.');const safe=detected(bytes)===m.mime;const key=`${m.organizationId}/${m.id}/original`;await store(key,bytes);await tx.update(media).set({storageKey:key,state:safe?'received':'quarantine',reviewReason:safe?'Réception vérifiée ; examen humain nécessaire.':'Signature de fichier inattendue. Diffusion bloquée.'}).where(eq(media.id,id));return {id:m.id,state:safe?'received':'quarantine'};});},
 async download(a:Actor,org:string,id:string){z.uuid().parse(id);const [m]=await db.select().from(media).where(and(eq(media.id,id),eq(media.organizationId,org)));if(!m)throw new AccessError();await access(db,a,org,m.projectId);if(!m.storageKey||m.state==='quarantine'||m.state==='uploading'||m.proposalState==='refused'||m.proposalState==='pending')throw new ProductionError('Fichier non disponible pour ce téléchargement.');const bytes=await read(m.storageKey);if(hash(bytes)!==m.sha256)throw new ProductionError('Intégrité du fichier non confirmée.');return {m,bytes};},
 async review(a:Actor,org:string,id:string,revision:number,approve:boolean,motif:string){motif=reason.parse(motif);return db.transaction(async tx=>{await lock(tx,org);const [m]=await tx.select().from(media).where(and(eq(media.id,id),eq(media.organizationId,org)));if(!m)throw new AccessError();const {p}=await access(tx,a,org,m.projectId,'edit');await active(tx,p,m.occurrenceId);if(m.revision!==revision||!['received','controlled'].includes(m.state)||m.proposalState==='pending'||m.proposalState==='refused')throw new ProductionError('Fichier à actualiser ou encore en attente de classement.');await tx.update(media).set({state:approve?'controlled':'quarantine',reviewReason:motif,reviewedBy:a.user.id,revision:m.revision+1}).where(eq(media.id,id));await tx.insert(productionHistory).values({organizationId:org,projectId:m.projectId,actorId:a.user.id,action:'media_review',reason:motif});});},
 async proposal(a:Actor,org:string,id:string,target:string|null,motif:string){motif=reason.parse(motif);return db.transaction(async tx=>{await lock(tx,org);const [m]=await tx.select().from(media).where(and(eq(media.id,id),eq(media.organizationId,org)));if(!m||m.proposalState!=='pending')throw new ProductionError('Proposition indisponible.');await access(tx,a,org,m.projectId,'edit');if(target){const {p}=await access(tx,a,org,target,'edit');await active(tx,p,null);}await tx.update(media).set({proposalState:target?'accepted':'refused',projectId:target||m.projectId,occurrenceId:target?null:m.occurrenceId,revision:m.revision+1,note:motif}).where(eq(media.id,id));});}
 };
}
