import {StatusComment} from '../../../../components/task-action-fields';
import Link from 'next/link';
import { randomUUID } from 'node:crypto';
import { programmeContext,MissingSpace } from '../../../../modules/programme/context';
import { workService } from '../../../../modules/work/service';
import { AccessError } from '../../../../modules/team/service';
import { requestLabels,requestTransitions,packNames,type RequestStatus } from '../../../../modules/work/models';
import { WorkForm } from '../../../../components/work-form';
import { TaskFields,Reason } from '../../../../components/work-fields';
import { Badge } from '../../../../components/ui/badge';
export const dynamic='force-dynamic';
export const metadata={title:'Préparation du projet'};
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{organisation?:string}>}){
 const {actor,db,org}=await programmeContext((await searchParams).organisation);if(!org)return <MissingSpace/>;let d;try{d=await workService(db).get(actor,org.id,(await params).id);}catch(e){if(e instanceof AccessError)return <MissingSpace/>;throw e;}const p=d.project,b=d.brief;const fields={organizationId:org.id,projectId:p.id};const active=p.status==='preparation'&&b.status==='accepted';const canDecide=d.canEdit&&(d.member.role==='admin'||d.member.id===b.decisionMakerId||d.member.id===p.deputyId);
 const Scope=()=>p.kind==='event'?<label>Occurrence<select name="occurrenceId" required>{d.events.filter(e=>e.status!=='cancelled').map(e=><option key={e.id} value={e.id}>{e.startDate}</option>)}</select></label>:<p>Campagne du {p.startDate} au {p.endDate}.</p>;
 return <><section className="page-title"><p className="eyebrow">PRÉPARATION · {org.name}</p><h1>{p.title}</h1><p>Demande, préparation et engagements de l’équipe.</p></section><div className="quick-actions"><Link className="button secondary" href={`/projets/${p.id}?organisation=${org.id}`}>Fiche projet</Link><Link className="button secondary" href={`/taches?organisation=${org.id}`}>Toutes les tâches</Link></div><section className="card"><h2>Traiter la demande</h2><Badge tone={b.status==='accepted'?'success':'warning'}>{requestLabels[b.status as RequestStatus]}</Badge><p>{b.objective}</p><p>Public : {b.audience}</p><p className="preserve-text">{b.message}</p><p>Ressources : {b.resources||'À préciser'} · Date utile : {b.usefulDate||'À préciser'}</p>{b.decisionReason&&<p>Dernière décision : {b.decisionReason}</p>}{canDecide&&p.status==='preparation'&&<WorkForm key={b.revision} fields={{...fields,operation:'decide',revision:b.revision}}><StatusComment options={requestTransitions[b.status as RequestStatus].map(s=>({value:s,label:requestLabels[s]}))}/><p>Reporter suspend le travail. Corriger un brief accepté demande une nouvelle décision.</p><button>Enregistrer la décision</button></WorkForm>}</section>
 {active&&d.canEdit&&<div className="grid section-spaced"><section className="card"><h2>Préparer un pack</h2><p>Choisissez les étapes et leurs dates dans l’aperçu. Aucune mission n’est acceptée automatiquement.</p><WorkForm fields={{...fields,operation:'preview'}}><Scope/><label>Pack<select name="pack" defaultValue={p.communicationLevel}>{Object.entries(packNames).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label>Dates déjà dépassées<select name="shift"><option value="yes">Répartir à partir d’aujourd’hui</option><option value="no">Conserver les dates initiales pour les revoir</option></select></label><button>Prévisualiser les tâches</button></WorkForm></section><section className="card"><h2>Ajouter une tâche</h2><WorkForm fields={{...fields,operation:'create',key:randomUUID()}}><Scope/><TaskFields people={d.candidates}/><Reason/><button>Créer la tâche</button></WorkForm></section></div>}
 {!active&&<p className="gentle-note">Les tâches restent conservées. La préparation reprend lorsque le projet est actif et la demande acceptée.</p>}
 <section className="card section-spaced"><h2>Tâches du projet</h2>{!d.tasks.length?<p>Aucune tâche créée.</p>:<ul className="item-list">{d.tasks.map(t=><li key={t.id}><Link href={`/taches/${t.id}?organisation=${org.id}&projet=${p.id}`}>{t.title}</Link><span>Échéance : {t.dueDate}</span></li>)}</ul>}</section>
 <section className="card section-spaced"><h2>Disponibilités et charge visible</h2>{(!p.validatorId || !d.candidates.some(c=>c.member.id===p.validatorId) || d.availability.some(v=>v.memberId===p.validatorId&&v.capacity==='unavailable'&&v.startDate<=p.endDate&&v.endDate>=p.startDate))&&<p className="gentle-note">Validation à organiser : le validateur est à désigner, son accès est à revoir ou une indisponibilité est déclarée sur la période. Aucun suppléant ne reçoit automatiquement le droit de valider. Vérifiez la fiche projet et les permissions dans Équipe.</p>}<p>Seules les personnes ayant accès au projet sont proposées. L’absence de déclaration ne signifie pas disponibilité. En cas de chevauchement, retenez la déclaration la plus restrictive.</p>{d.candidates.map(c=><div key={c.member.id}><h3>{c.name||c.email}</h3><p>{d.tasks.filter(t=>t.assigneeId===c.member.id&&t.status!=='done').length} tâche(s) ouverte(s) dans ce projet.</p><ul>{d.availability.filter(v=>v.memberId===c.member.id).map(v=><li key={v.id}>{v.startDate} → {v.endDate} : {{available:'Disponible',limited:'Disponibilité limitée',unavailable:'Indisponible'}[v.capacity]} {v.note}</li>)}</ul></div>)}</section><section className="gentle-note"><h2>Historique</h2><ul>{d.history.map(h=><li key={h.id}>{h.createdAt.toLocaleDateString('fr-FR',{timeZone:p.timezone})} · {h.reason}</li>)}</ul></section></>;
}
