import {and,eq,asc,or,lt} from 'drizzle-orm';
import {randomUUID,timingSafeEqual} from 'node:crypto';
import {z} from 'zod';
import {driveTransfers,media,productionHistory} from '../../db/production-schema';
import {user} from '../../db/auth-schema';
import {type DB,type Conn,access,active,lock,ProductionError} from '../production/access';
import {type Actor,AccessError} from '../team/service';
import {hash,read} from '../production/storage';
export type DriveConfig={organizationId:string;folderId:string;token:string};
const googleId=z.string().regex(/^[A-Za-z0-9_-]{10,200}$/);
export function driveConfig():DriveConfig|null{const parsed=z.object({organizationId:z.uuid(),folderId:googleId,token:z.string().min(32).max(512)}).safeParse({organizationId:process.env.N8N_ORGANIZATION_ID,folderId:process.env.GOOGLE_DRIVE_FOLDER_ID,token:process.env.N8N_SERVICE_TOKEN});return parsed.success?parsed.data:null;}
export function authenticateWorker(header:string|null,config:DriveConfig|null){if(!config)throw new AccessError('Connexion n8n non configurée.');const supplied=header?.startsWith('Bearer ')?header.slice(7):'';if(!timingSafeEqual(Buffer.from(hash(supplied)),Buffer.from(hash(config.token))))throw new AccessError('Accès au transfert refusé.');return config;}
const receiptSchema=z.object({id:googleId,size:z.string().regex(/^\d+$/),sha256Checksum:z.string().regex(/^[a-f0-9]{64}$/),parents:z.array(googleId).min(1).max(10),trashed:z.literal(false),mimeType:z.string().optional(),appProperties:z.object({cometernelJob:z.uuid()})});
export function driveTransferService(db:DB,config:DriveConfig){
 async function source(c:Conn,id:string,actor:Actor){const [m]=await c.select().from(media).where(and(eq(media.id,id),eq(media.organizationId,config.organizationId)));if(!m)throw new AccessError();const {p,m:member}=await access(c,actor,config.organizationId,m.projectId,'edit');if(member.role!=='admin')throw new AccessError();await active(c,p,m.occurrenceId);if(m.state!=='controlled'||!m.storageKey||['pending','refused'].includes(m.proposalState||'')||m.rights?.withdrawn)throw new ProductionError('Le fichier doit être contrôlé, classé et sans retrait de droits.');return m;}
 async function actorFor(c:Conn,id:string):Promise<Actor>{const [u]=await c.select().from(user).where(eq(user.id,id));if(!u?.emailVerified)throw new AccessError();return {user:{id:u.id,email:u.email,emailVerified:u.emailVerified},session:{createdAt:new Date()}};}
 async function leased(c:Conn,id:string,leaseId:string){z.uuid().parse(id);z.uuid().parse(leaseId);const [job]=await c.select().from(driveTransfers).where(and(eq(driveTransfers.id,id),eq(driveTransfers.organizationId,config.organizationId),eq(driveTransfers.folderId,config.folderId)));if(!job||job.leaseId!==leaseId||!job.leaseUntil||job.leaseUntil<=new Date()||!['running','succeeded'].includes(job.status))throw new ProductionError('Transfert expiré ou indisponible.');const m=await source(c,job.mediaId,await actorFor(c,job.createdBy));return {job,m};}
 return {
 async enqueue(actor:Actor,id:string){z.uuid().parse(id);return db.transaction(async tx=>{await lock(tx,config.organizationId);const m=await source(tx,id,actor);if(m.size>5*1024*1024)throw new ProductionError('Le premier test Drive est limité à 5 Mo par fichier.');const [old]=await tx.select().from(driveTransfers).where(and(eq(driveTransfers.organizationId,config.organizationId),eq(driveTransfers.mediaId,id),eq(driveTransfers.folderId,config.folderId)));if(old&&['queued','running','succeeded'].includes(old.status))return old;const values={organizationId:config.organizationId,mediaId:id,folderId:config.folderId,createdBy:actor.user.id};const [job]=old?await tx.update(driveTransfers).set({...values,status:'queued',attempts:0,leaseId:null,leaseUntil:null,errorCode:null}).where(eq(driveTransfers.id,old.id)).returning():await tx.insert(driveTransfers).values(values).returning();await tx.insert(productionHistory).values({organizationId:config.organizationId,projectId:m.projectId,actorId:actor.user.id,action:'drive_transfer_requested',reason:'Transfert Drive demandé explicitement vers le dossier configuré.'});return job;});},
 async claim(requestId:string){z.string().regex(/^[A-Za-z0-9_-]{1,100}$/).parse(requestId);return db.transaction(async tx=>{await lock(tx,config.organizationId);const [previous]=await tx.select().from(driveTransfers).where(and(eq(driveTransfers.organizationId,config.organizationId),eq(driveTransfers.requestId,requestId)));if(previous){if(previous.status!=='running'||!previous.leaseUntil||previous.leaseUntil<=new Date()||previous.folderId!==config.folderId)return {job:null};const {m}=await leased(tx,previous.id,previous.leaseId!);return {job:{id:previous.id,leaseId:previous.leaseId!,mediaId:m.id,name:m.name,mime:m.mime,size:m.size,sha256:m.sha256,folderId:previous.folderId,driveFileId:previous.driveFileId}};}const candidates=await tx.select().from(driveTransfers).where(and(eq(driveTransfers.organizationId,config.organizationId),eq(driveTransfers.folderId,config.folderId),or(eq(driveTransfers.status,'queued'),and(eq(driveTransfers.status,'running'),lt(driveTransfers.leaseUntil,new Date()))))).orderBy(asc(driveTransfers.createdAt)).limit(20);for(const job of candidates){if(job.attempts>=3){await tx.update(driveTransfers).set({status:'failed',errorCode:'retry_limit'}).where(eq(driveTransfers.id,job.id));continue;}let m;try{m=await source(tx,job.mediaId,await actorFor(tx,job.createdBy));}catch{await tx.update(driveTransfers).set({status:'suspended',errorCode:'source_unavailable'}).where(eq(driveTransfers.id,job.id));continue;}const leaseId=randomUUID();await tx.update(driveTransfers).set({status:'running',requestId,leaseId,leaseUntil:new Date(Date.now()+20*60000),attempts:job.attempts+1,errorCode:null}).where(eq(driveTransfers.id,job.id));return {job:{id:job.id,leaseId,mediaId:m.id,name:m.name,mime:m.mime,size:m.size,sha256:m.sha256,folderId:job.folderId,driveFileId:job.driveFileId}};}return {job:null};});},
 async reserve(id:string,input:unknown){const v=z.object({leaseId:z.uuid(),driveFileId:googleId}).parse(input);return db.transaction(async tx=>{await lock(tx,config.organizationId);const {job}=await leased(tx,id,v.leaseId);if(job.status!=='running')throw new ProductionError('Transfert déjà terminé.');if(job.driveFileId)return {driveFileId:job.driveFileId};await tx.update(driveTransfers).set({driveFileId:v.driveFileId}).where(eq(driveTransfers.id,id));return {driveFileId:v.driveFileId};});},
 async file(id:string,leaseId:string){return db.transaction(async tx=>{await lock(tx,config.organizationId);const {job,m}=await leased(tx,id,leaseId);if(job.status!=='running')throw new ProductionError('Transfert déjà terminé.');const bytes=await read(m.storageKey!);if(bytes.length!==m.size||hash(bytes)!==m.sha256)throw new ProductionError('Intégrité du fichier à vérifier.');return {bytes,name:m.name};});},
 async result(id:string,input:unknown){const v=z.discriminatedUnion('status',[z.object({status:z.literal('succeeded'),leaseId:z.uuid(),driveFile:receiptSchema}),z.object({status:z.literal('failed'),leaseId:z.uuid(),errorCode:z.enum(['transfer_failed','metadata_mismatch','source_unavailable'])})]).parse(input);return db.transaction(async tx=>{await lock(tx,config.organizationId);const {job,m}=await leased(tx,id,v.leaseId);if(v.status==='succeeded'){const f=v.driveFile;if(!job.driveFileId||f.id!==job.driveFileId||Number(f.size)!==m.size||f.sha256Checksum!==m.sha256||!f.parents.includes(job.folderId)||f.appProperties.cometernelJob!==job.id||(f.mimeType&&f.mimeType!==m.mime))throw new ProductionError('La copie Drive ne correspond pas au fichier attendu.');if(job.status==='succeeded')return {status:'succeeded'};await tx.update(driveTransfers).set({status:'succeeded',receipt:f,completedAt:new Date(),errorCode:null}).where(eq(driveTransfers.id,id));await tx.insert(productionHistory).values({organizationId:config.organizationId,projectId:m.projectId,actorId:job.createdBy,action:'drive_transfer_verified',reason:'n8n a confirmé la copie Drive, son dossier, sa taille et son empreinte.'});}else{if(job.status==='succeeded')throw new ProductionError('Transfert déjà confirmé.');await tx.update(driveTransfers).set({status:'failed',errorCode:v.errorCode,leaseId:null,leaseUntil:null}).where(eq(driveTransfers.id,id));}return {status:v.status};});}
 };
}
