import Link from 'next/link';
import {programmeContext,MissingSpace} from '../../../modules/programme/context';
import {programmeService} from '../../../modules/programme/service';
import {contentService} from '../../../modules/production/content-service';
import {ProductionForm} from '../../../components/production-form';
import {ContentFields} from '../../../components/content-fields';
import {Badge} from '../../../components/ui/badge';
export const dynamic='force-dynamic';export const metadata={title:'Contenu, validation et diffusion'};
export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{organisation?:string}>}){const {actor,db,org}=await programmeContext((await searchParams).organisation);if(!org)return <MissingSpace/>;let d;try{d=await contentService(db).get(actor,org.id,(await params).id);}catch{return <MissingSpace/>;}const {item:c,version:v}=d;const fields={organizationId:org.id,projectId:c.projectId,id:c.id,revision:c.revision,creationKey:c.creationKey};const events=(await programmeService(db).get(actor,org.id,c.projectId)).events;return <><section className="page-title"><p className="eyebrow">{d.project.title} · {c.channel} · {c.plannedDate}</p><h1>{c.title}</h1><Badge tone={d.ready?'success':'warning'}>Version {v.number} · {d.ready?'Accord et droits vérifiés':'À revoir avant diffusion'}</Badge><p>{d.blocker}</p></section><Link href={`/contenus?organisation=${org.id}`}>Tous les contenus</Link><section className="card section-spaced"><h2>Texte de la version {v.number}</h2><p className="preserve-text">{v.caption}</p><p>{v.reference}</p>{v.practicalUrl&&<a href={v.practicalUrl} target="_blank" rel="noopener noreferrer">Informations pratiques</a>}{v.creationUrl&&<p><a href={v.creationUrl} target="_blank" rel="noopener noreferrer">Outil de création</a></p>}<ul>{v.mediaIds.map(id=><li key={id}><Link href={`/medias/${id}?organisation=${org.id}`}>{d.assets.find(m=>m.id===id)?.name||'Fichier indisponible'}</Link></li>)}</ul></section>
 {d.canEdit&&d.project.status==='preparation'&&<section className="card section-spaced"><h2>Modifier la création</h2><details><summary>Créer une nouvelle version</summary><ProductionForm key={`edit-${c.revision}`} fields={{...fields,operation:'save'}}><ContentFields item={c} version={v} assets={d.assets} events={events}/><p>Une nouvelle version devra être approuvée. Les anciens accords et paquets ne s’appliquent pas à cette version.</p><button>Enregistrer une nouvelle version</button></ProductionForm></details>{['draft','changes'].includes(c.status)&&<ProductionForm key={`submit-${c.revision}`} fields={{...fields,operation:'submit'}}><button>Soumettre à la validation</button></ProductionForm>}</section>}
 <section className="card section-spaced"><h2>Relecture et décisions</h2><ProductionForm key={`decision-${c.revision}`} fields={{...fields,operation:'decide'}}><label>Action<select name="decision"><option value="comment">Ajouter un commentaire</option>{d.canValidate&&<><option value="approved">Approuver cette version et ce canal</option><option value="changes">Demander des corrections</option></>}</select></label><label>Commentaire / motif<textarea name="reason" minLength={5} maxLength={3000} required/></label><button>Enregistrer</button></ProductionForm><ul>{d.history.map(h=><li key={h.id}>{h.decision==='approved'?'Approbation':h.decision==='changes'?'Corrections':'Commentaire'} · {h.reason}</li>)}</ul></section>
 {d.canEdit&&<section className="card section-spaced"><h2>Diffusion manuelle</h2><p>ComÉternel prépare le travail. Vous publiez vous-même sur le canal choisi, puis déclarez la diffusion réelle.</p>{d.ready&&<><ProductionForm fields={{...fields,operation:'prepare'}}><label>Responsable des réponses<input name="responseOwner" minLength={2} maxLength={150} required/></label><button>Préparer le paquet manuel</button></ProductionForm><a className="button secondary" href={`/api/contenus/${c.id}?organisation=${org.id}`}>Télécharger le texte et les références</a><ProductionForm fields={{...fields,operation:'publish'}}><label>Lien ou preuve précise de diffusion<textarea name="proof" minLength={8} maxLength={2000} required/></label><label>Date et heure réelles avec fuseau<input name="publishedAt" placeholder="2026-09-20T10:30:00-04:00" required/></label><button>Déclarer la diffusion effectuée</button></ProductionForm></>}<ul className="item-list">{d.publications.map(pub=><li key={pub.id}><strong>{{prepared:'Paquet préparé',published:'Diffusion déclarée',obsolete:'Paquet périmé',withdrawn:'Retrait à traiter'}[pub.status]}</strong><span>{pub.proof||'Aucune diffusion déclarée'} · Réponses : {pub.responseOwner}</span>{pub.versionId!==v.id&&<Badge tone="warning">Ancienne version · Vérifier les copies diffusées</Badge>}</li>)}</ul><details><summary>Demander un retrait / signaler une erreur</summary><ProductionForm fields={{...fields,operation:'withdraw'}}><label>Motif<textarea name="reason" minLength={5} required/></label><p>Bloque la préparation dans l’application. Le retrait effectif sur chaque canal reste à réaliser et vérifier manuellement.</p><button>Enregistrer le retrait à traiter</button></ProductionForm></details></section>}
 <section className="gentle-note"><h2>Versions conservées</h2>{d.versions.map(old=><details key={old.id}><summary>Version {old.number} · {old.channel}</summary><p className="preserve-text">{old.caption}</p><p>{old.brief}</p></details>)}</section></>;}
